package modelv;
// Generated Jan 8, 2016 7:39:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewMenu generated by hbm2java
 */
@Entity
@Table(name="view_menu"
    ,catalog="vxsee"
)
public class ViewMenu  implements java.io.Serializable {


     private Integer object_rights_id;
     private Integer canview;
     private Integer childcaptavailable;
     private String childcapticon;
     private Integer childcaptid;
     private Integer childcaptindustryid;
          private Integer childcaptcompanyid;

     private String childcaptislarge;
     private String childcaptname;
     private Integer childcaptobjectcaptionsort;
     private Integer childcaptquicklink;
     private String childcaptreportpath;
     private String childcaptsetpath;
     private Integer childhasnotification;
     private Integer childhasreportsubmenu;
     private Integer childisbuttonselect;
     private Integer childisbuttonselectwithmenu;
     private Integer childisgraph;
     private Integer childisreport;
     private String childobjectcode;
     private Integer childobjectid;
     private Integer childobjectlevel;
     private String childobjectname;
     private Integer childparentid;
     private String parentcaption;
     private Integer parentcaptionavailable;
     private String parentcaptionislarge;
     private Integer parentcaptionobjectid;
     private String parentcaptionobjectname;
     private Integer parentcaptionquicklink;
     private String parentcaptionsetpath;
     private Integer parentcaptionsort;
     private Integer parentcaptobjectcaptionid;
     private Integer parenthasnotification;
     private Integer parenthasreportsubmenu;
     private Integer parentindustryid;
     private Integer parentisbuttonselect;
     private Integer parentisbuttonselectwithmenu;
     private Integer parentisgraph;
     private Integer parentisreport;
     private Integer parentobjectid;
     private Integer parentobjectlevel;
     private String parentobjectname;
     private String parentscaptionicon;
     private Integer profile_id;

    public ViewMenu() {
    }

	
    public ViewMenu(Integer object_rights_id) {
        this.object_rights_id = object_rights_id;
    }
    public ViewMenu(Integer object_rights_id, Integer canview, Integer childcaptavailable, String childcapticon, Integer childcaptid, Integer childcaptindustryid,Integer childcaptcompanyid, String childcaptislarge, String childcaptname, Integer childcaptobjectcaptionsort, Integer childcaptquicklink, String childcaptreportpath, String childcaptsetpath, Integer childhasnotification, Integer childhasreportsubmenu, Integer childisbuttonselect, Integer childisbuttonselectwithmenu, Integer childisgraph, Integer childisreport, String childobjectcode, Integer childobjectid, Integer childobjectlevel, String childobjectname, Integer childparentid, String parentcaption, Integer parentcaptionavailable, String parentcaptionislarge, Integer parentcaptionobjectid, String parentcaptionobjectname, Integer parentcaptionquicklink, String parentcaptionsetpath, Integer parentcaptionsort, Integer parentcaptobjectcaptionid, Integer parenthasnotification, Integer parenthasreportsubmenu, Integer parentindustryid, Integer parentisbuttonselect, Integer parentisbuttonselectwithmenu, Integer parentisgraph, Integer parentisreport, Integer parentobjectid, Integer parentobjectlevel, String parentobjectname, String parentscaptionicon, Integer profile_id) {
       this.object_rights_id = object_rights_id;
       this.canview = canview;
       this.childcaptavailable = childcaptavailable;
       this.childcapticon = childcapticon;
       this.childcaptid = childcaptid;
       this.childcaptindustryid = childcaptindustryid;
              this.childcaptcompanyid = childcaptcompanyid;

       this.childcaptislarge = childcaptislarge;
       this.childcaptname = childcaptname;
       this.childcaptobjectcaptionsort = childcaptobjectcaptionsort;
       this.childcaptquicklink = childcaptquicklink;
       this.childcaptreportpath = childcaptreportpath;
       this.childcaptsetpath = childcaptsetpath;
       this.childhasnotification = childhasnotification;
       this.childhasreportsubmenu = childhasreportsubmenu;
       this.childisbuttonselect = childisbuttonselect;
       this.childisbuttonselectwithmenu = childisbuttonselectwithmenu;
       this.childisgraph = childisgraph;
       this.childisreport = childisreport;
       this.childobjectcode = childobjectcode;
       this.childobjectid = childobjectid;
       this.childobjectlevel = childobjectlevel;
       this.childobjectname = childobjectname;
       this.childparentid = childparentid;
       this.parentcaption = parentcaption;
       this.parentcaptionavailable = parentcaptionavailable;
       this.parentcaptionislarge = parentcaptionislarge;
       this.parentcaptionobjectid = parentcaptionobjectid;
       this.parentcaptionobjectname = parentcaptionobjectname;
       this.parentcaptionquicklink = parentcaptionquicklink;
       this.parentcaptionsetpath = parentcaptionsetpath;
       this.parentcaptionsort = parentcaptionsort;
       this.parentcaptobjectcaptionid = parentcaptobjectcaptionid;
       this.parenthasnotification = parenthasnotification;
       this.parenthasreportsubmenu = parenthasreportsubmenu;
       this.parentindustryid = parentindustryid;
       this.parentisbuttonselect = parentisbuttonselect;
       this.parentisbuttonselectwithmenu = parentisbuttonselectwithmenu;
       this.parentisgraph = parentisgraph;
       this.parentisreport = parentisreport;
       this.parentobjectid = parentobjectid;
       this.parentobjectlevel = parentobjectlevel;
       this.parentobjectname = parentobjectname;
       this.parentscaptionicon = parentscaptionicon;
       this.profile_id = profile_id;
    }
   
     @Id 

    
    @Column(name=" object_rights_id ", nullable=false)
    public Integer getObject_rights_id() {
        return this.object_rights_id;
    }
    
    public void setObject_rights_id(Integer object_rights_id) {
        this.object_rights_id = object_rights_id;
    }

    
    @Column(name="canview")
    public Integer getCanview() {
        return this.canview;
    }
    
    public void setCanview(Integer canview) {
        this.canview = canview;
    }

    
    @Column(name="childcaptavailable")
    public Integer getChildcaptavailable() {
        return this.childcaptavailable;
    }
    
    public void setChildcaptavailable(Integer childcaptavailable) {
        this.childcaptavailable = childcaptavailable;
    }

    
    @Column(name="childcapticon")
    public String getChildcapticon() {
        return this.childcapticon;
    }
    
    public void setChildcapticon(String childcapticon) {
        this.childcapticon = childcapticon;
    }

    
    @Column(name="childcaptid")
    public Integer getChildcaptid() {
        return this.childcaptid;
    }
    
    public void setChildcaptid(Integer childcaptid) {
        this.childcaptid = childcaptid;
    }

    
    @Column(name="childcaptindustryid")
    public Integer getChildcaptindustryid() {
        return this.childcaptindustryid;
    }
    
    public void setChildcaptindustryid(Integer childcaptindustryid) {
        this.childcaptindustryid = childcaptindustryid;
    }
 @Column(name="childcaptcompanyid")
    public Integer getChildcaptcompanyid() {
        return this.childcaptcompanyid;
    }
    
    public void setChildcaptcompanyid(Integer childcaptcompanyid) {
        this.childcaptcompanyid = childcaptcompanyid;
    }
    
    @Column(name="childcaptislarge")
    public String getChildcaptislarge() {
        return this.childcaptislarge;
    }
    
    public void setChildcaptislarge(String childcaptislarge) {
        this.childcaptislarge = childcaptislarge;
    }

    
    @Column(name="childcaptname")
    public String getChildcaptname() {
        return this.childcaptname;
    }
    
    public void setChildcaptname(String childcaptname) {
        this.childcaptname = childcaptname;
    }

    
    @Column(name="childcaptobjectcaptionsort")
    public Integer getChildcaptobjectcaptionsort() {
        return this.childcaptobjectcaptionsort;
    }
    
    public void setChildcaptobjectcaptionsort(Integer childcaptobjectcaptionsort) {
        this.childcaptobjectcaptionsort = childcaptobjectcaptionsort;
    }

    
    @Column(name="childcaptquicklink")
    public Integer getChildcaptquicklink() {
        return this.childcaptquicklink;
    }
    
    public void setChildcaptquicklink(Integer childcaptquicklink) {
        this.childcaptquicklink = childcaptquicklink;
    }

    
    @Column(name="childcaptreportpath")
    public String getChildcaptreportpath() {
        return this.childcaptreportpath;
    }
    
    public void setChildcaptreportpath(String childcaptreportpath) {
        this.childcaptreportpath = childcaptreportpath;
    }

    
    @Column(name="childcaptsetpath")
    public String getChildcaptsetpath() {
        return this.childcaptsetpath;
    }
    
    public void setChildcaptsetpath(String childcaptsetpath) {
        this.childcaptsetpath = childcaptsetpath;
    }

    
    @Column(name="childhasnotification")
    public Integer getChildhasnotification() {
        return this.childhasnotification;
    }
    
    public void setChildhasnotification(Integer childhasnotification) {
        this.childhasnotification = childhasnotification;
    }

    
    @Column(name="childhasreportsubmenu")
    public Integer getChildhasreportsubmenu() {
        return this.childhasreportsubmenu;
    }
    
    public void setChildhasreportsubmenu(Integer childhasreportsubmenu) {
        this.childhasreportsubmenu = childhasreportsubmenu;
    }

    
    @Column(name="childisbuttonselect")
    public Integer getChildisbuttonselect() {
        return this.childisbuttonselect;
    }
    
    public void setChildisbuttonselect(Integer childisbuttonselect) {
        this.childisbuttonselect = childisbuttonselect;
    }

    
    @Column(name="childisbuttonselectwithmenu")
    public Integer getChildisbuttonselectwithmenu() {
        return this.childisbuttonselectwithmenu;
    }
    
    public void setChildisbuttonselectwithmenu(Integer childisbuttonselectwithmenu) {
        this.childisbuttonselectwithmenu = childisbuttonselectwithmenu;
    }

    
    @Column(name="childisgraph")
    public Integer getChildisgraph() {
        return this.childisgraph;
    }
    
    public void setChildisgraph(Integer childisgraph) {
        this.childisgraph = childisgraph;
    }

    
    @Column(name="childisreport")
    public Integer getChildisreport() {
        return this.childisreport;
    }
    
    public void setChildisreport(Integer childisreport) {
        this.childisreport = childisreport;
    }

    
    @Column(name="childobjectcode")
    public String getChildobjectcode() {
        return this.childobjectcode;
    }
    
    public void setChildobjectcode(String childobjectcode) {
        this.childobjectcode = childobjectcode;
    }

    
    @Column(name="childobjectid")
    public Integer getChildobjectid() {
        return this.childobjectid;
    }
    
    public void setChildobjectid(Integer childobjectid) {
        this.childobjectid = childobjectid;
    }

    
    @Column(name="childobjectlevel")
    public Integer getChildobjectlevel() {
        return this.childobjectlevel;
    }
    
    public void setChildobjectlevel(Integer childobjectlevel) {
        this.childobjectlevel = childobjectlevel;
    }

    
    @Column(name="childobjectname")
    public String getChildobjectname() {
        return this.childobjectname;
    }
    
    public void setChildobjectname(String childobjectname) {
        this.childobjectname = childobjectname;
    }

    
    @Column(name="childparentid")
    public Integer getChildparentid() {
        return this.childparentid;
    }
    
    public void setChildparentid(Integer childparentid) {
        this.childparentid = childparentid;
    }

    
    @Column(name="parentcaption")
    public String getParentcaption() {
        return this.parentcaption;
    }
    
    public void setParentcaption(String parentcaption) {
        this.parentcaption = parentcaption;
    }

    
    @Column(name="parentcaptionavailable")
    public Integer getParentcaptionavailable() {
        return this.parentcaptionavailable;
    }
    
    public void setParentcaptionavailable(Integer parentcaptionavailable) {
        this.parentcaptionavailable = parentcaptionavailable;
    }

    
    @Column(name="parentcaptionislarge")
    public String getParentcaptionislarge() {
        return this.parentcaptionislarge;
    }
    
    public void setParentcaptionislarge(String parentcaptionislarge) {
        this.parentcaptionislarge = parentcaptionislarge;
    }

    
    @Column(name="parentcaptionobjectid")
    public Integer getParentcaptionobjectid() {
        return this.parentcaptionobjectid;
    }
    
    public void setParentcaptionobjectid(Integer parentcaptionobjectid) {
        this.parentcaptionobjectid = parentcaptionobjectid;
    }

    
    @Column(name="parentcaptionobjectname")
    public String getParentcaptionobjectname() {
        return this.parentcaptionobjectname;
    }
    
    public void setParentcaptionobjectname(String parentcaptionobjectname) {
        this.parentcaptionobjectname = parentcaptionobjectname;
    }

    
    @Column(name="parentcaptionquicklink")
    public Integer getParentcaptionquicklink() {
        return this.parentcaptionquicklink;
    }
    
    public void setParentcaptionquicklink(Integer parentcaptionquicklink) {
        this.parentcaptionquicklink = parentcaptionquicklink;
    }

    
    @Column(name="parentcaptionsetpath")
    public String getParentcaptionsetpath() {
        return this.parentcaptionsetpath;
    }
    
    public void setParentcaptionsetpath(String parentcaptionsetpath) {
        this.parentcaptionsetpath = parentcaptionsetpath;
    }

    
    @Column(name="parentcaptionsort")
    public Integer getParentcaptionsort() {
        return this.parentcaptionsort;
    }
    
    public void setParentcaptionsort(Integer parentcaptionsort) {
        this.parentcaptionsort = parentcaptionsort;
    }

    
    @Column(name="parentcaptobjectcaptionid")
    public Integer getParentcaptobjectcaptionid() {
        return this.parentcaptobjectcaptionid;
    }
    
    public void setParentcaptobjectcaptionid(Integer parentcaptobjectcaptionid) {
        this.parentcaptobjectcaptionid = parentcaptobjectcaptionid;
    }

    
    @Column(name="parenthasnotification")
    public Integer getParenthasnotification() {
        return this.parenthasnotification;
    }
    
    public void setParenthasnotification(Integer parenthasnotification) {
        this.parenthasnotification = parenthasnotification;
    }

    
    @Column(name="parenthasreportsubmenu")
    public Integer getParenthasreportsubmenu() {
        return this.parenthasreportsubmenu;
    }
    
    public void setParenthasreportsubmenu(Integer parenthasreportsubmenu) {
        this.parenthasreportsubmenu = parenthasreportsubmenu;
    }

    
    @Column(name="parentindustryid")
    public Integer getParentindustryid() {
        return this.parentindustryid;
    }
    
    public void setParentindustryid(Integer parentindustryid) {
        this.parentindustryid = parentindustryid;
    }

    
    @Column(name="parentisbuttonselect")
    public Integer getParentisbuttonselect() {
        return this.parentisbuttonselect;
    }
    
    public void setParentisbuttonselect(Integer parentisbuttonselect) {
        this.parentisbuttonselect = parentisbuttonselect;
    }

    
    @Column(name="parentisbuttonselectwithmenu")
    public Integer getParentisbuttonselectwithmenu() {
        return this.parentisbuttonselectwithmenu;
    }
    
    public void setParentisbuttonselectwithmenu(Integer parentisbuttonselectwithmenu) {
        this.parentisbuttonselectwithmenu = parentisbuttonselectwithmenu;
    }

    
    @Column(name="parentisgraph")
    public Integer getParentisgraph() {
        return this.parentisgraph;
    }
    
    public void setParentisgraph(Integer parentisgraph) {
        this.parentisgraph = parentisgraph;
    }

    
    @Column(name="parentisreport")
    public Integer getParentisreport() {
        return this.parentisreport;
    }
    
    public void setParentisreport(Integer parentisreport) {
        this.parentisreport = parentisreport;
    }

    
    @Column(name="parentobjectid")
    public Integer getParentobjectid() {
        return this.parentobjectid;
    }
    
    public void setParentobjectid(Integer parentobjectid) {
        this.parentobjectid = parentobjectid;
    }

    
    @Column(name="parentobjectlevel")
    public Integer getParentobjectlevel() {
        return this.parentobjectlevel;
    }
    
    public void setParentobjectlevel(Integer parentobjectlevel) {
        this.parentobjectlevel = parentobjectlevel;
    }

    
    @Column(name="parentobjectname")
    public String getParentobjectname() {
        return this.parentobjectname;
    }
    
    public void setParentobjectname(String parentobjectname) {
        this.parentobjectname = parentobjectname;
    }

    
    @Column(name="parentscaptionicon")
    public String getParentscaptionicon() {
        return this.parentscaptionicon;
    }
    
    public void setParentscaptionicon(String parentscaptionicon) {
        this.parentscaptionicon = parentscaptionicon;
    }

    
    @Column(name=" profile_id ")
    public Integer getProfile_id() {
        return this.profile_id;
    }
    
    public void setProfile_id(Integer profile_id) {
        this.profile_id = profile_id;
    }




}


