package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BankAccount1 generated by hbm2java
 */
@Entity
@Table(name="bank_account1"
    ,catalog="vxsee"
)
public class BankAccount1  implements java.io.Serializable {


     private Integer accountId;
     private String accountName;
     private int chartId;
     private int bankId;
     private Integer currencyId;
     private String accountNumber;
     private String type;
     private boolean default_;
     private boolean activeInd;
     private int createBy;
     private Date createDt;
     private int modBy;
     private Date modDt;

    public BankAccount1() {
    }

	
    public BankAccount1(String accountName, int chartId, int bankId, String accountNumber, String type, boolean default_, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
        this.accountName = accountName;
        this.chartId = chartId;
        this.bankId = bankId;
        this.accountNumber = accountNumber;
        this.type = type;
        this.default_ = default_;
        this.activeInd = activeInd;
        this.createBy = createBy;
        this.createDt = createDt;
        this.modBy = modBy;
        this.modDt = modDt;
    }
    public BankAccount1(String accountName, int chartId, int bankId, Integer currencyId, String accountNumber, String type, boolean default_, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
       this.accountName = accountName;
       this.chartId = chartId;
       this.bankId = bankId;
       this.currencyId = currencyId;
       this.accountNumber = accountNumber;
       this.type = type;
       this.default_ = default_;
       this.activeInd = activeInd;
       this.createBy = createBy;
       this.createDt = createDt;
       this.modBy = modBy;
       this.modDt = modDt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Account_ID", unique=true, nullable=false)
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    
    @Column(name="Account_Name", nullable=false, length=100)
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    
    @Column(name="Chart_ID", nullable=false)
    public int getChartId() {
        return this.chartId;
    }
    
    public void setChartId(int chartId) {
        this.chartId = chartId;
    }

    
    @Column(name="Bank_ID", nullable=false)
    public int getBankId() {
        return this.bankId;
    }
    
    public void setBankId(int bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="Currency_ID")
    public Integer getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    
    @Column(name="Account_Number", nullable=false, length=100)
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    
    @Column(name="Type", nullable=false, length=2)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="Default", nullable=false)
    public boolean isDefault_() {
        return this.default_;
    }
    
    public void setDefault_(boolean default_) {
        this.default_ = default_;
    }

    
    @Column(name="ActiveInd", nullable=false)
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="CreateBy", nullable=false)
    public int getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(int createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDt", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ModBy", nullable=false)
    public int getModBy() {
        return this.modBy;
    }
    
    public void setModBy(int modBy) {
        this.modBy = modBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModDt", nullable=false, length=19)
    public Date getModDt() {
        return this.modDt;
    }
    
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }




}


