package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Branch1 generated by hbm2java
 */
@Entity
@Table(name="branch1"
    ,catalog="vxsee"
)
public class Branch1  implements java.io.Serializable {


     private Integer branchId;
     private String branchCode;
     private String branch;
     private int bankId;
     private boolean activeInd;
     private int createBy;
     private Date createDt;
     private int modBy;
     private Date modDt;

    public Branch1() {
    }

	
    public Branch1(String branch, int bankId, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
        this.branch = branch;
        this.bankId = bankId;
        this.activeInd = activeInd;
        this.createBy = createBy;
        this.createDt = createDt;
        this.modBy = modBy;
        this.modDt = modDt;
    }
    public Branch1(String branchCode, String branch, int bankId, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
       this.branchCode = branchCode;
       this.branch = branch;
       this.bankId = bankId;
       this.activeInd = activeInd;
       this.createBy = createBy;
       this.createDt = createDt;
       this.modBy = modBy;
       this.modDt = modDt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Branch_ID", unique=true, nullable=false)
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    
    @Column(name="Branch_Code", length=50)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="Branch", nullable=false, length=200)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    
    @Column(name="Bank_ID", nullable=false)
    public int getBankId() {
        return this.bankId;
    }
    
    public void setBankId(int bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="ActiveInd", nullable=false)
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="CreateBy", nullable=false)
    public int getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(int createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDt", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ModBy", nullable=false)
    public int getModBy() {
        return this.modBy;
    }
    
    public void setModBy(int modBy) {
        this.modBy = modBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModDt", nullable=false, length=19)
    public Date getModDt() {
        return this.modDt;
    }
    
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }




}


