package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConIndustry generated by hbm2java
 */
@Entity
@Table(name="con_industry"
    ,catalog="vxsee"
)
public class ConIndustry  implements java.io.Serializable {


     private Integer industryId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private String industry;
     private String industryCode;
     private Date createdt;
     private Date writedt;
     private Set<ConCompany> conCompanies = new HashSet<ConCompany>(0);
     private Set<ConObjectscaption> conObjectscaptions = new HashSet<ConObjectscaption>(0);

    public ConIndustry() {
    }

	
    public ConIndustry(ConLife conLife, String industry) {
        this.conLife = conLife;
        this.industry = industry;
    }
    public ConIndustry(ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, String industry, String industryCode, Date createdt, Date writedt, Set<ConCompany> conCompanies, Set<ConObjectscaption> conObjectscaptions) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.industry = industry;
       this.industryCode = industryCode;
       this.createdt = createdt;
       this.writedt = writedt;
       this.conCompanies = conCompanies;
       this.conObjectscaptions = conObjectscaptions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="industry_id", unique=true, nullable=false)
    public Integer getIndustryId() {
        return this.industryId;
    }
    
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

    
    @Column(name="industry", nullable=false, length=100)
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    
    @Column(name="industry_code", length=50)
    public String getIndustryCode() {
        return this.industryCode;
    }
    
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conIndustry")
    public Set<ConCompany> getConCompanies() {
        return this.conCompanies;
    }
    
    public void setConCompanies(Set<ConCompany> conCompanies) {
        this.conCompanies = conCompanies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conIndustry")
    public Set<ConObjectscaption> getConObjectscaptions() {
        return this.conObjectscaptions;
    }
    
    public void setConObjectscaptions(Set<ConObjectscaption> conObjectscaptions) {
        this.conObjectscaptions = conObjectscaptions;
    }




}


