package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConObjectrights generated by hbm2java
 */
@Entity
@Table(name="con_objectrights"
    ,catalog="vxsee"
)
public class ConObjectrights  implements java.io.Serializable {


     private Integer objectRightsId;
     private ConLife conLife;
     private ConObjects conObjects;
     private ConProfiles conProfiles;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private boolean canview;
     private boolean canadd;
     private boolean canedit;
     private boolean candel;
     private boolean canauthorize;
     private boolean canapprove;
     private boolean canexport;
     private Date createdt;
     private Date writedt;

    public ConObjectrights() {
    }

	
    public ConObjectrights(ConLife conLife, ConObjects conObjects, ConProfiles conProfiles, boolean canview, boolean canadd, boolean canedit, boolean candel, boolean canauthorize, boolean canapprove, boolean canexport) {
        this.conLife = conLife;
        this.conObjects = conObjects;
        this.conProfiles = conProfiles;
        this.canview = canview;
        this.canadd = canadd;
        this.canedit = canedit;
        this.candel = candel;
        this.canauthorize = canauthorize;
        this.canapprove = canapprove;
        this.canexport = canexport;
    }
    public ConObjectrights(ConLife conLife, ConObjects conObjects, ConProfiles conProfiles, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, boolean canview, boolean canadd, boolean canedit, boolean candel, boolean canauthorize, boolean canapprove, boolean canexport, Date createdt, Date writedt) {
       this.conLife = conLife;
       this.conObjects = conObjects;
       this.conProfiles = conProfiles;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.canview = canview;
       this.canadd = canadd;
       this.canedit = canedit;
       this.candel = candel;
       this.canauthorize = canauthorize;
       this.canapprove = canapprove;
       this.canexport = canexport;
       this.createdt = createdt;
       this.writedt = writedt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="object_rights_id", unique=true, nullable=false)
    public Integer getObjectRightsId() {
        return this.objectRightsId;
    }
    
    public void setObjectRightsId(Integer objectRightsId) {
        this.objectRightsId = objectRightsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="object_id", nullable=false)
    public ConObjects getConObjects() {
        return this.conObjects;
    }
    
    public void setConObjects(ConObjects conObjects) {
        this.conObjects = conObjects;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profile_id", nullable=false)
    public ConProfiles getConProfiles() {
        return this.conProfiles;
    }
    
    public void setConProfiles(ConProfiles conProfiles) {
        this.conProfiles = conProfiles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

    
    @Column(name="canview", nullable=false)
    public boolean isCanview() {
        return this.canview;
    }
    
    public void setCanview(boolean canview) {
        this.canview = canview;
    }

    
    @Column(name="canadd", nullable=false)
    public boolean isCanadd() {
        return this.canadd;
    }
    
    public void setCanadd(boolean canadd) {
        this.canadd = canadd;
    }

    
    @Column(name="canedit", nullable=false)
    public boolean isCanedit() {
        return this.canedit;
    }
    
    public void setCanedit(boolean canedit) {
        this.canedit = canedit;
    }

    
    @Column(name="candel", nullable=false)
    public boolean isCandel() {
        return this.candel;
    }
    
    public void setCandel(boolean candel) {
        this.candel = candel;
    }

    
    @Column(name="canauthorize", nullable=false)
    public boolean isCanauthorize() {
        return this.canauthorize;
    }
    
    public void setCanauthorize(boolean canauthorize) {
        this.canauthorize = canauthorize;
    }

    
    @Column(name="canapprove", nullable=false)
    public boolean isCanapprove() {
        return this.canapprove;
    }
    
    public void setCanapprove(boolean canapprove) {
        this.canapprove = canapprove;
    }

    
    @Column(name="canexport", nullable=false)
    public boolean isCanexport() {
        return this.canexport;
    }
    
    public void setCanexport(boolean canexport) {
        this.canexport = canexport;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }




}


