package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConProfiles generated by hbm2java
 */
@Entity
@Table(name="con_profiles"
    ,catalog="vxsee"
)
public class ConProfiles  implements java.io.Serializable {


     private Integer profileId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private String profileName;
     private Date createdt;
     private Date writedt;
     private Set<ConUser> conUsers = new HashSet<ConUser>(0);
     private Set<ConAuth> conAuths = new HashSet<ConAuth>(0);
     private Set<ConObjectrights> conObjectrightses = new HashSet<ConObjectrights>(0);

    public ConProfiles() {
    }

	
    public ConProfiles(ConLife conLife) {
        this.conLife = conLife;
    }
    public ConProfiles(ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, String profileName, Date createdt, Date writedt, Set<ConUser> conUsers, Set<ConAuth> conAuths, Set<ConObjectrights> conObjectrightses) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.profileName = profileName;
       this.createdt = createdt;
       this.writedt = writedt;
       this.conUsers = conUsers;
       this.conAuths = conAuths;
       this.conObjectrightses = conObjectrightses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="profile_id", unique=true, nullable=false)
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

    
    @Column(name="profile_name", length=30)
    public String getProfileName() {
        return this.profileName;
    }
    
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conProfiles")
    public Set<ConUser> getConUsers() {
        return this.conUsers;
    }
    
    public void setConUsers(Set<ConUser> conUsers) {
        this.conUsers = conUsers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conProfiles")
    public Set<ConAuth> getConAuths() {
        return this.conAuths;
    }
    
    public void setConAuths(Set<ConAuth> conAuths) {
        this.conAuths = conAuths;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conProfiles")
    public Set<ConObjectrights> getConObjectrightses() {
        return this.conObjectrightses;
    }
    
    public void setConObjectrightses(Set<ConObjectrights> conObjectrightses) {
        this.conObjectrightses = conObjectrightses;
    }




}


