package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmCustomer generated by hbm2java
 */
@Entity
@Table(name="crm_customer"
    ,catalog="vxsee"
)
public class CrmCustomer  implements java.io.Serializable {


     private Integer customerId;
     private AllCountry allCountry;
     private CommonCombo commonCombo;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private CrmCustomerCategory crmCustomerCategory;
     private HrmEmployee hrmEmployee;
     private Payterm payterm;
     private Date admnDate;
     private String customerCode;
     private String surname;
     private String othername;
     private Integer idNo;
     private String vatNo;
     private String pinNo;
     private String memo;
     private Boolean credit;
     private BigDecimal creditLimit;
     private String contactPerson;
     private String primaryMobileNo;
     private String primaryLandline;
     private String primaryEmail;
     private String boxAddress;
     private String boxAddressCode;
     private String boxAddressTown;
     private String physicalAddress;
     private Date createdt;
     private Date writedt;
     private Set<CrmSalesinvoice> crmSalesinvoices = new HashSet<CrmSalesinvoice>(0);
     private Set<CrmDelivery> crmDeliveries = new HashSet<CrmDelivery>(0);
     private Set<MfcJobcard> mfcJobcards = new HashSet<MfcJobcard>(0);
     private Set<CrmQuote> crmQuotes = new HashSet<CrmQuote>(0);
     private Set<ItemCustomPrices> itemCustomPriceses = new HashSet<ItemCustomPrices>(0);
     private Set<CrmSalesorder> crmSalesorders = new HashSet<CrmSalesorder>(0);
     private Set<FinReceipt> finReceipts = new HashSet<FinReceipt>(0);

    public CrmCustomer() {
    }

    public CrmCustomer(AllCountry allCountry, CommonCombo commonCombo, ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, CrmCustomerCategory crmCustomerCategory, HrmEmployee hrmEmployee, Payterm payterm, Date admnDate, String customerCode, String surname, String othername, Integer idNo, String vatNo, String pinNo, String memo, Boolean credit, BigDecimal creditLimit, String contactPerson, String primaryMobileNo, String primaryLandline, String primaryEmail, String boxAddress, String boxAddressCode, String boxAddressTown, String physicalAddress, Date createdt, Date writedt, Set<CrmSalesinvoice> crmSalesinvoices, Set<CrmDelivery> crmDeliveries, Set<MfcJobcard> mfcJobcards, Set<CrmQuote> crmQuotes, Set<ItemCustomPrices> itemCustomPriceses, Set<CrmSalesorder> crmSalesorders, Set<FinReceipt> finReceipts) {
       this.allCountry = allCountry;
       this.commonCombo = commonCombo;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.crmCustomerCategory = crmCustomerCategory;
       this.hrmEmployee = hrmEmployee;
       this.payterm = payterm;
       this.admnDate = admnDate;
       this.customerCode = customerCode;
       this.surname = surname;
       this.othername = othername;
       this.idNo = idNo;
       this.vatNo = vatNo;
       this.pinNo = pinNo;
       this.memo = memo;
       this.credit = credit;
       this.creditLimit = creditLimit;
       this.contactPerson = contactPerson;
       this.primaryMobileNo = primaryMobileNo;
       this.primaryLandline = primaryLandline;
       this.primaryEmail = primaryEmail;
       this.boxAddress = boxAddress;
       this.boxAddressCode = boxAddressCode;
       this.boxAddressTown = boxAddressTown;
       this.physicalAddress = physicalAddress;
       this.createdt = createdt;
       this.writedt = writedt;
       this.crmSalesinvoices = crmSalesinvoices;
       this.crmDeliveries = crmDeliveries;
       this.mfcJobcards = mfcJobcards;
       this.crmQuotes = crmQuotes;
       this.itemCustomPriceses = itemCustomPriceses;
       this.crmSalesorders = crmSalesorders;
       this.finReceipts = finReceipts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id")
    public AllCountry getAllCountry() {
        return this.allCountry;
    }
    
    public void setAllCountry(AllCountry allCountry) {
        this.allCountry = allCountry;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="title")
    public CommonCombo getCommonCombo() {
        return this.commonCombo;
    }
    
    public void setCommonCombo(CommonCombo commonCombo) {
        this.commonCombo = commonCombo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_category_id")
    public CrmCustomerCategory getCrmCustomerCategory() {
        return this.crmCustomerCategory;
    }
    
    public void setCrmCustomerCategory(CrmCustomerCategory crmCustomerCategory) {
        this.crmCustomerCategory = crmCustomerCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agent_id")
    public HrmEmployee getHrmEmployee() {
        return this.hrmEmployee;
    }
    
    public void setHrmEmployee(HrmEmployee hrmEmployee) {
        this.hrmEmployee = hrmEmployee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payterm_id")
    public Payterm getPayterm() {
        return this.payterm;
    }
    
    public void setPayterm(Payterm payterm) {
        this.payterm = payterm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="admn_date", length=19)
    public Date getAdmnDate() {
        return this.admnDate;
    }
    
    public void setAdmnDate(Date admnDate) {
        this.admnDate = admnDate;
    }

    
    @Column(name="customer_code", length=15)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="surname", length=20)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="othername", length=40)
    public String getOthername() {
        return this.othername;
    }
    
    public void setOthername(String othername) {
        this.othername = othername;
    }

    
    @Column(name="id_no")
    public Integer getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(Integer idNo) {
        this.idNo = idNo;
    }

    
    @Column(name="vat_no", length=50)
    public String getVatNo() {
        return this.vatNo;
    }
    
    public void setVatNo(String vatNo) {
        this.vatNo = vatNo;
    }

    
    @Column(name="pin_no", length=50)
    public String getPinNo() {
        return this.pinNo;
    }
    
    public void setPinNo(String pinNo) {
        this.pinNo = pinNo;
    }

    
    @Column(name="memo", length=200)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="credit")
    public Boolean getCredit() {
        return this.credit;
    }
    
    public void setCredit(Boolean credit) {
        this.credit = credit;
    }

    
    @Column(name="credit_limit", precision=38, scale=20)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="contact_person", length=50)
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    
    @Column(name="primary_mobile_no", length=50)
    public String getPrimaryMobileNo() {
        return this.primaryMobileNo;
    }
    
    public void setPrimaryMobileNo(String primaryMobileNo) {
        this.primaryMobileNo = primaryMobileNo;
    }

    
    @Column(name="primary_landline", length=50)
    public String getPrimaryLandline() {
        return this.primaryLandline;
    }
    
    public void setPrimaryLandline(String primaryLandline) {
        this.primaryLandline = primaryLandline;
    }

    
    @Column(name="primary_email", length=50)
    public String getPrimaryEmail() {
        return this.primaryEmail;
    }
    
    public void setPrimaryEmail(String primaryEmail) {
        this.primaryEmail = primaryEmail;
    }

    
    @Column(name="box_address", length=50)
    public String getBoxAddress() {
        return this.boxAddress;
    }
    
    public void setBoxAddress(String boxAddress) {
        this.boxAddress = boxAddress;
    }

    
    @Column(name="box_address_code", length=10)
    public String getBoxAddressCode() {
        return this.boxAddressCode;
    }
    
    public void setBoxAddressCode(String boxAddressCode) {
        this.boxAddressCode = boxAddressCode;
    }

    
    @Column(name="box_address_town", length=50)
    public String getBoxAddressTown() {
        return this.boxAddressTown;
    }
    
    public void setBoxAddressTown(String boxAddressTown) {
        this.boxAddressTown = boxAddressTown;
    }

    
    @Column(name="physical_address", length=50)
    public String getPhysicalAddress() {
        return this.physicalAddress;
    }
    
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<CrmSalesinvoice> getCrmSalesinvoices() {
        return this.crmSalesinvoices;
    }
    
    public void setCrmSalesinvoices(Set<CrmSalesinvoice> crmSalesinvoices) {
        this.crmSalesinvoices = crmSalesinvoices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<CrmDelivery> getCrmDeliveries() {
        return this.crmDeliveries;
    }
    
    public void setCrmDeliveries(Set<CrmDelivery> crmDeliveries) {
        this.crmDeliveries = crmDeliveries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<MfcJobcard> getMfcJobcards() {
        return this.mfcJobcards;
    }
    
    public void setMfcJobcards(Set<MfcJobcard> mfcJobcards) {
        this.mfcJobcards = mfcJobcards;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<CrmQuote> getCrmQuotes() {
        return this.crmQuotes;
    }
    
    public void setCrmQuotes(Set<CrmQuote> crmQuotes) {
        this.crmQuotes = crmQuotes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<ItemCustomPrices> getItemCustomPriceses() {
        return this.itemCustomPriceses;
    }
    
    public void setItemCustomPriceses(Set<ItemCustomPrices> itemCustomPriceses) {
        this.itemCustomPriceses = itemCustomPriceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<CrmSalesorder> getCrmSalesorders() {
        return this.crmSalesorders;
    }
    
    public void setCrmSalesorders(Set<CrmSalesorder> crmSalesorders) {
        this.crmSalesorders = crmSalesorders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmCustomer")
    public Set<FinReceipt> getFinReceipts() {
        return this.finReceipts;
    }
    
    public void setFinReceipts(Set<FinReceipt> finReceipts) {
        this.finReceipts = finReceipts;
    }




}


