package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmUom generated by hbm2java
 */
@Entity
@Table(name="crm_uom"
    ,catalog="vxsee"
)
public class CrmUom  implements java.io.Serializable {


     private Integer uomId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private CrmUomCateg crmUomCateg;
     private String uomName;
     private Date createdt;
     private Date writedt;
     private Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForUomId = new HashSet<CrmSalesinvoiceLine>(0);
     private Set<InvAdjustments> invAdjustmentses = new HashSet<InvAdjustments>(0);
     private Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForDimensionUomId = new HashSet<CrmSalesinvoiceLine>(0);
     private Set<ItemPurchase> itemPurchases = new HashSet<ItemPurchase>(0);
     private Set<PrcPurchaseOrderLine> prcPurchaseOrderLines = new HashSet<PrcPurchaseOrderLine>(0);
     private Set<CrmQuoteLine> crmQuoteLinesForDimensionUomId = new HashSet<CrmQuoteLine>(0);
     private Set<CrmQuoteLine> crmQuoteLinesForUomId = new HashSet<CrmQuoteLine>(0);
     private Set<InvGoodsreceivedLine> invGoodsreceivedLinesForPurchaseuomId = new HashSet<InvGoodsreceivedLine>(0);
     private Set<InvGoodsreceivedLine> invGoodsreceivedLinesForReceiveduomId = new HashSet<InvGoodsreceivedLine>(0);
     private Set<PoDtl> poDtls = new HashSet<PoDtl>(0);
     private Set<ItemDimensions> itemDimensionses = new HashSet<ItemDimensions>(0);
     private Set<ItemSale> itemSales = new HashSet<ItemSale>(0);
     private Set<CrmDeliveryLine> crmDeliveryLinesForDimensionUomId = new HashSet<CrmDeliveryLine>(0);
     private Set<CrmSalesorderLine> crmSalesorderLinesForUomId = new HashSet<CrmSalesorderLine>(0);
     private Set<CrmSalesorderLine> crmSalesorderLinesForDimensionUomId = new HashSet<CrmSalesorderLine>(0);
     private Set<CrmDeliveryLine> crmDeliveryLinesForUomId = new HashSet<CrmDeliveryLine>(0);
     private Set<CrmPosLine> crmPosLinesForUomId = new HashSet<CrmPosLine>(0);
     private Set<MfcJobcardLine> mfcJobcardLinesForUomId = new HashSet<MfcJobcardLine>(0);
     private Set<MfcJobcardLine> mfcJobcardLinesForDimensionUomId = new HashSet<MfcJobcardLine>(0);
     private Set<CrmPosLine> crmPosLinesForDimensionUomId = new HashSet<CrmPosLine>(0);

    public CrmUom() {
    }

	
    public CrmUom(ConCompany conCompany) {
        this.conCompany = conCompany;
    }
    public CrmUom(ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, CrmUomCateg crmUomCateg, String uomName, Date createdt, Date writedt, Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForUomId, Set<InvAdjustments> invAdjustmentses, Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForDimensionUomId, Set<ItemPurchase> itemPurchases, Set<PrcPurchaseOrderLine> prcPurchaseOrderLines, Set<CrmQuoteLine> crmQuoteLinesForDimensionUomId, Set<CrmQuoteLine> crmQuoteLinesForUomId, Set<InvGoodsreceivedLine> invGoodsreceivedLinesForPurchaseuomId, Set<InvGoodsreceivedLine> invGoodsreceivedLinesForReceiveduomId, Set<PoDtl> poDtls, Set<ItemDimensions> itemDimensionses, Set<ItemSale> itemSales, Set<CrmDeliveryLine> crmDeliveryLinesForDimensionUomId, Set<CrmSalesorderLine> crmSalesorderLinesForUomId, Set<CrmSalesorderLine> crmSalesorderLinesForDimensionUomId, Set<CrmDeliveryLine> crmDeliveryLinesForUomId, Set<CrmPosLine> crmPosLinesForUomId, Set<MfcJobcardLine> mfcJobcardLinesForUomId, Set<MfcJobcardLine> mfcJobcardLinesForDimensionUomId, Set<CrmPosLine> crmPosLinesForDimensionUomId) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.crmUomCateg = crmUomCateg;
       this.uomName = uomName;
       this.createdt = createdt;
       this.writedt = writedt;
       this.crmSalesinvoiceLinesForUomId = crmSalesinvoiceLinesForUomId;
       this.invAdjustmentses = invAdjustmentses;
       this.crmSalesinvoiceLinesForDimensionUomId = crmSalesinvoiceLinesForDimensionUomId;
       this.itemPurchases = itemPurchases;
       this.prcPurchaseOrderLines = prcPurchaseOrderLines;
       this.crmQuoteLinesForDimensionUomId = crmQuoteLinesForDimensionUomId;
       this.crmQuoteLinesForUomId = crmQuoteLinesForUomId;
       this.invGoodsreceivedLinesForPurchaseuomId = invGoodsreceivedLinesForPurchaseuomId;
       this.invGoodsreceivedLinesForReceiveduomId = invGoodsreceivedLinesForReceiveduomId;
       this.poDtls = poDtls;
       this.itemDimensionses = itemDimensionses;
       this.itemSales = itemSales;
       this.crmDeliveryLinesForDimensionUomId = crmDeliveryLinesForDimensionUomId;
       this.crmSalesorderLinesForUomId = crmSalesorderLinesForUomId;
       this.crmSalesorderLinesForDimensionUomId = crmSalesorderLinesForDimensionUomId;
       this.crmDeliveryLinesForUomId = crmDeliveryLinesForUomId;
       this.crmPosLinesForUomId = crmPosLinesForUomId;
       this.mfcJobcardLinesForUomId = mfcJobcardLinesForUomId;
       this.mfcJobcardLinesForDimensionUomId = mfcJobcardLinesForDimensionUomId;
       this.crmPosLinesForDimensionUomId = crmPosLinesForDimensionUomId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="uom_id", unique=true, nullable=false)
    public Integer getUomId() {
        return this.uomId;
    }
    
    public void setUomId(Integer uomId) {
        this.uomId = uomId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uom_category_id")
    public CrmUomCateg getCrmUomCateg() {
        return this.crmUomCateg;
    }
    
    public void setCrmUomCateg(CrmUomCateg crmUomCateg) {
        this.crmUomCateg = crmUomCateg;
    }

    
    @Column(name="uom_name", length=50)
    public String getUomName() {
        return this.uomName;
    }
    
    public void setUomName(String uomName) {
        this.uomName = uomName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<CrmSalesinvoiceLine> getCrmSalesinvoiceLinesForUomId() {
        return this.crmSalesinvoiceLinesForUomId;
    }
    
    public void setCrmSalesinvoiceLinesForUomId(Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForUomId) {
        this.crmSalesinvoiceLinesForUomId = crmSalesinvoiceLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<InvAdjustments> getInvAdjustmentses() {
        return this.invAdjustmentses;
    }
    
    public void setInvAdjustmentses(Set<InvAdjustments> invAdjustmentses) {
        this.invAdjustmentses = invAdjustmentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<CrmSalesinvoiceLine> getCrmSalesinvoiceLinesForDimensionUomId() {
        return this.crmSalesinvoiceLinesForDimensionUomId;
    }
    
    public void setCrmSalesinvoiceLinesForDimensionUomId(Set<CrmSalesinvoiceLine> crmSalesinvoiceLinesForDimensionUomId) {
        this.crmSalesinvoiceLinesForDimensionUomId = crmSalesinvoiceLinesForDimensionUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<ItemPurchase> getItemPurchases() {
        return this.itemPurchases;
    }
    
    public void setItemPurchases(Set<ItemPurchase> itemPurchases) {
        this.itemPurchases = itemPurchases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<PrcPurchaseOrderLine> getPrcPurchaseOrderLines() {
        return this.prcPurchaseOrderLines;
    }
    
    public void setPrcPurchaseOrderLines(Set<PrcPurchaseOrderLine> prcPurchaseOrderLines) {
        this.prcPurchaseOrderLines = prcPurchaseOrderLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<CrmQuoteLine> getCrmQuoteLinesForDimensionUomId() {
        return this.crmQuoteLinesForDimensionUomId;
    }
    
    public void setCrmQuoteLinesForDimensionUomId(Set<CrmQuoteLine> crmQuoteLinesForDimensionUomId) {
        this.crmQuoteLinesForDimensionUomId = crmQuoteLinesForDimensionUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<CrmQuoteLine> getCrmQuoteLinesForUomId() {
        return this.crmQuoteLinesForUomId;
    }
    
    public void setCrmQuoteLinesForUomId(Set<CrmQuoteLine> crmQuoteLinesForUomId) {
        this.crmQuoteLinesForUomId = crmQuoteLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByPurchaseuomId")
    public Set<InvGoodsreceivedLine> getInvGoodsreceivedLinesForPurchaseuomId() {
        return this.invGoodsreceivedLinesForPurchaseuomId;
    }
    
    public void setInvGoodsreceivedLinesForPurchaseuomId(Set<InvGoodsreceivedLine> invGoodsreceivedLinesForPurchaseuomId) {
        this.invGoodsreceivedLinesForPurchaseuomId = invGoodsreceivedLinesForPurchaseuomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByReceiveduomId")
    public Set<InvGoodsreceivedLine> getInvGoodsreceivedLinesForReceiveduomId() {
        return this.invGoodsreceivedLinesForReceiveduomId;
    }
    
    public void setInvGoodsreceivedLinesForReceiveduomId(Set<InvGoodsreceivedLine> invGoodsreceivedLinesForReceiveduomId) {
        this.invGoodsreceivedLinesForReceiveduomId = invGoodsreceivedLinesForReceiveduomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<PoDtl> getPoDtls() {
        return this.poDtls;
    }
    
    public void setPoDtls(Set<PoDtl> poDtls) {
        this.poDtls = poDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<ItemDimensions> getItemDimensionses() {
        return this.itemDimensionses;
    }
    
    public void setItemDimensionses(Set<ItemDimensions> itemDimensionses) {
        this.itemDimensionses = itemDimensionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUom")
    public Set<ItemSale> getItemSales() {
        return this.itemSales;
    }
    
    public void setItemSales(Set<ItemSale> itemSales) {
        this.itemSales = itemSales;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<CrmDeliveryLine> getCrmDeliveryLinesForDimensionUomId() {
        return this.crmDeliveryLinesForDimensionUomId;
    }
    
    public void setCrmDeliveryLinesForDimensionUomId(Set<CrmDeliveryLine> crmDeliveryLinesForDimensionUomId) {
        this.crmDeliveryLinesForDimensionUomId = crmDeliveryLinesForDimensionUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<CrmSalesorderLine> getCrmSalesorderLinesForUomId() {
        return this.crmSalesorderLinesForUomId;
    }
    
    public void setCrmSalesorderLinesForUomId(Set<CrmSalesorderLine> crmSalesorderLinesForUomId) {
        this.crmSalesorderLinesForUomId = crmSalesorderLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<CrmSalesorderLine> getCrmSalesorderLinesForDimensionUomId() {
        return this.crmSalesorderLinesForDimensionUomId;
    }
    
    public void setCrmSalesorderLinesForDimensionUomId(Set<CrmSalesorderLine> crmSalesorderLinesForDimensionUomId) {
        this.crmSalesorderLinesForDimensionUomId = crmSalesorderLinesForDimensionUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<CrmDeliveryLine> getCrmDeliveryLinesForUomId() {
        return this.crmDeliveryLinesForUomId;
    }
    
    public void setCrmDeliveryLinesForUomId(Set<CrmDeliveryLine> crmDeliveryLinesForUomId) {
        this.crmDeliveryLinesForUomId = crmDeliveryLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<CrmPosLine> getCrmPosLinesForUomId() {
        return this.crmPosLinesForUomId;
    }
    
    public void setCrmPosLinesForUomId(Set<CrmPosLine> crmPosLinesForUomId) {
        this.crmPosLinesForUomId = crmPosLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByUomId")
    public Set<MfcJobcardLine> getMfcJobcardLinesForUomId() {
        return this.mfcJobcardLinesForUomId;
    }
    
    public void setMfcJobcardLinesForUomId(Set<MfcJobcardLine> mfcJobcardLinesForUomId) {
        this.mfcJobcardLinesForUomId = mfcJobcardLinesForUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<MfcJobcardLine> getMfcJobcardLinesForDimensionUomId() {
        return this.mfcJobcardLinesForDimensionUomId;
    }
    
    public void setMfcJobcardLinesForDimensionUomId(Set<MfcJobcardLine> mfcJobcardLinesForDimensionUomId) {
        this.mfcJobcardLinesForDimensionUomId = mfcJobcardLinesForDimensionUomId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="crmUomByDimensionUomId")
    public Set<CrmPosLine> getCrmPosLinesForDimensionUomId() {
        return this.crmPosLinesForDimensionUomId;
    }
    
    public void setCrmPosLinesForDimensionUomId(Set<CrmPosLine> crmPosLinesForDimensionUomId) {
        this.crmPosLinesForDimensionUomId = crmPosLinesForDimensionUomId;
    }




}


