package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinReceiptLine generated by hbm2java
 */
@Entity
@Table(name="fin_receipt_line"
    ,catalog="vxsee"
)
public class FinReceiptLine  implements java.io.Serializable {


     private Integer receiptLineId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private FinReceipt finReceipt;
     private Integer salesinvoiceId;
     private BigDecimal amount;
     private BigDecimal amountPaid;
     private BigDecimal balance;
     private Integer cr;
     private Integer paymodeId;
     private String memo;
     private Date createdt;
     private Date writedt;

    public FinReceiptLine() {
    }

    public FinReceiptLine(ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, FinReceipt finReceipt, Integer salesinvoiceId, BigDecimal amount, BigDecimal amountPaid, BigDecimal balance, Integer cr, Integer paymodeId, String memo, Date createdt, Date writedt) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.finReceipt = finReceipt;
       this.salesinvoiceId = salesinvoiceId;
       this.amount = amount;
       this.amountPaid = amountPaid;
       this.balance = balance;
       this.cr = cr;
       this.paymodeId = paymodeId;
       this.memo = memo;
       this.createdt = createdt;
       this.writedt = writedt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="receipt_line_id", unique=true, nullable=false)
    public Integer getReceiptLineId() {
        return this.receiptLineId;
    }
    
    public void setReceiptLineId(Integer receiptLineId) {
        this.receiptLineId = receiptLineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="receipt_id")
    public FinReceipt getFinReceipt() {
        return this.finReceipt;
    }
    
    public void setFinReceipt(FinReceipt finReceipt) {
        this.finReceipt = finReceipt;
    }

    
    @Column(name="salesinvoice_id")
    public Integer getSalesinvoiceId() {
        return this.salesinvoiceId;
    }
    
    public void setSalesinvoiceId(Integer salesinvoiceId) {
        this.salesinvoiceId = salesinvoiceId;
    }

    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="amount_paid", precision=10, scale=4)
    public BigDecimal getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    
    @Column(name="balance", precision=10, scale=4)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="cr")
    public Integer getCr() {
        return this.cr;
    }
    
    public void setCr(Integer cr) {
        this.cr = cr;
    }

    
    @Column(name="paymode_id")
    public Integer getPaymodeId() {
        return this.paymodeId;
    }
    
    public void setPaymodeId(Integer paymodeId) {
        this.paymodeId = paymodeId;
    }

    
    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }




}


