package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinReceipt generated by hbm2java
 */
@Entity
@Table(name="fin_receipt"
    ,catalog="vxsee"
)
public class FinReceipt  implements java.io.Serializable {


     private Integer receiptId;
     private AllStatus allStatus;
     private Bank bank;
     private Branch branch;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private CrmCustomer crmCustomer;
     private PrcSuppliers prcSuppliers;
     private String receiptNo;
     private String receiptType;
     private String ref;
     private Date receiptDate;
     private BigDecimal amount;
     private BigDecimal discount;
     private Integer cr;
     private Integer dr;
     private String payer;
     private String rctMemo;
     private Boolean posted;
     private Date postDate;
     private Boolean paid;
     private Integer seq;
     private Date createdt;
     private Date writedt;
     private Set<FinReceiptLine> finReceiptLines = new HashSet<FinReceiptLine>(0);

    public FinReceipt() {
    }

	
    public FinReceipt(BigDecimal discount) {
        this.discount = discount;
    }
    public FinReceipt(AllStatus allStatus, Bank bank, Branch branch, ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, CrmCustomer crmCustomer, PrcSuppliers prcSuppliers, String receiptNo, String receiptType, String ref, Date receiptDate, BigDecimal amount, BigDecimal discount, Integer cr, Integer dr, String payer, String rctMemo, Boolean posted, Date postDate, Boolean paid, Integer seq, Date createdt, Date writedt, Set<FinReceiptLine> finReceiptLines) {
       this.allStatus = allStatus;
       this.bank = bank;
       this.branch = branch;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.crmCustomer = crmCustomer;
       this.prcSuppliers = prcSuppliers;
       this.receiptNo = receiptNo;
       this.receiptType = receiptType;
       this.ref = ref;
       this.receiptDate = receiptDate;
       this.amount = amount;
       this.discount = discount;
       this.cr = cr;
       this.dr = dr;
       this.payer = payer;
       this.rctMemo = rctMemo;
       this.posted = posted;
       this.postDate = postDate;
       this.paid = paid;
       this.seq = seq;
       this.createdt = createdt;
       this.writedt = writedt;
       this.finReceiptLines = finReceiptLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="receipt_id", unique=true, nullable=false)
    public Integer getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public AllStatus getAllStatus() {
        return this.allStatus;
    }
    
    public void setAllStatus(AllStatus allStatus) {
        this.allStatus = allStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bank_id")
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="branch_id")
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public CrmCustomer getCrmCustomer() {
        return this.crmCustomer;
    }
    
    public void setCrmCustomer(CrmCustomer crmCustomer) {
        this.crmCustomer = crmCustomer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public PrcSuppliers getPrcSuppliers() {
        return this.prcSuppliers;
    }
    
    public void setPrcSuppliers(PrcSuppliers prcSuppliers) {
        this.prcSuppliers = prcSuppliers;
    }

    
    @Column(name="receipt_no", length=20)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="receipt_type", length=2)
    public String getReceiptType() {
        return this.receiptType;
    }
    
    public void setReceiptType(String receiptType) {
        this.receiptType = receiptType;
    }

    
    @Column(name="ref")
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="receipt_date", length=10)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="discount", nullable=false, precision=10)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="cr")
    public Integer getCr() {
        return this.cr;
    }
    
    public void setCr(Integer cr) {
        this.cr = cr;
    }

    
    @Column(name="dr")
    public Integer getDr() {
        return this.dr;
    }
    
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    
    @Column(name="payer", length=200)
    public String getPayer() {
        return this.payer;
    }
    
    public void setPayer(String payer) {
        this.payer = payer;
    }

    
    @Column(name="rct_memo", length=65535)
    public String getRctMemo() {
        return this.rctMemo;
    }
    
    public void setRctMemo(String rctMemo) {
        this.rctMemo = rctMemo;
    }

    
    @Column(name="posted")
    public Boolean getPosted() {
        return this.posted;
    }
    
    public void setPosted(Boolean posted) {
        this.posted = posted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="post_date", length=10)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="paid")
    public Boolean getPaid() {
        return this.paid;
    }
    
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    
    @Column(name="seq")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="finReceipt")
    public Set<FinReceiptLine> getFinReceiptLines() {
        return this.finReceiptLines;
    }
    
    public void setFinReceiptLines(Set<FinReceiptLine> finReceiptLines) {
        this.finReceiptLines = finReceiptLines;
    }




}


