package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinVat generated by hbm2java
 */
@Entity
@Table(name="fin_vat"
    ,catalog="vxsee"
)
public class FinVat  implements java.io.Serializable {


     private int vatId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private String vatName;
     private BigDecimal vatRate;
     private Date createdt;
     private Date writedt;
     private Set<ItemSale> itemSales = new HashSet<ItemSale>(0);
     private Set<ItemPurchase> itemPurchases = new HashSet<ItemPurchase>(0);

    public FinVat() {
    }

	
    public FinVat(int vatId, String vatName, BigDecimal vatRate) {
        this.vatId = vatId;
        this.vatName = vatName;
        this.vatRate = vatRate;
    }
    public FinVat(int vatId, ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, String vatName, BigDecimal vatRate, Date createdt, Date writedt, Set<ItemSale> itemSales, Set<ItemPurchase> itemPurchases) {
       this.vatId = vatId;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.vatName = vatName;
       this.vatRate = vatRate;
       this.createdt = createdt;
       this.writedt = writedt;
       this.itemSales = itemSales;
       this.itemPurchases = itemPurchases;
    }
   
     @Id 

    
    @Column(name="vat_id", unique=true, nullable=false)
    public int getVatId() {
        return this.vatId;
    }
    
    public void setVatId(int vatId) {
        this.vatId = vatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

    
    @Column(name="vat_name", nullable=false, length=50)
    public String getVatName() {
        return this.vatName;
    }
    
    public void setVatName(String vatName) {
        this.vatName = vatName;
    }

    
    @Column(name="vat_rate", nullable=false, precision=10)
    public BigDecimal getVatRate() {
        return this.vatRate;
    }
    
    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="finVat")
    public Set<ItemSale> getItemSales() {
        return this.itemSales;
    }
    
    public void setItemSales(Set<ItemSale> itemSales) {
        this.itemSales = itemSales;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="finVat")
    public Set<ItemPurchase> getItemPurchases() {
        return this.itemPurchases;
    }
    
    public void setItemPurchases(Set<ItemPurchase> itemPurchases) {
        this.itemPurchases = itemPurchases;
    }




}


