package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvGoodsreceivedLine generated by hbm2java
 */
@Entity
@Table(name="inv_goodsreceived_line"
    ,catalog="vxsee"
)
public class InvGoodsreceivedLine  implements java.io.Serializable {


     private Integer grnLineId;
     private AllStatus allStatus;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private CrmUom crmUomByPurchaseuomId;
     private CrmUom crmUomByReceiveduomId;
     private InvGoodsreceived invGoodsreceived;
     private InvStore invStore;
     private Item item;
     private Date recievedDate;
     private String ref;
     private String batchNo;
     private String purchaseqty;
     private BigDecimal purchaseuomQty;
     private Integer purchaseunits;
     private BigDecimal purchasePrice;
     private Integer receivedqty;
     private Integer receivedunits;
     private BigDecimal receivedprice;
     private BigDecimal receiveduomQty;
     private BigDecimal utilizedQty;
     private BigDecimal returnedQty;
     private Date manufactureDate;
     private Date expiryDate;
     private BigDecimal vatAmount;
     private Date createdt;
     private Date writedt;

    public InvGoodsreceivedLine() {
    }

	
    public InvGoodsreceivedLine(BigDecimal vatAmount) {
        this.vatAmount = vatAmount;
    }
    public InvGoodsreceivedLine(AllStatus allStatus, ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, CrmUom crmUomByPurchaseuomId, CrmUom crmUomByReceiveduomId, InvGoodsreceived invGoodsreceived, InvStore invStore, Item item, Date recievedDate, String ref, String batchNo, String purchaseqty, BigDecimal purchaseuomQty, Integer purchaseunits, BigDecimal purchasePrice, Integer receivedqty, Integer receivedunits, BigDecimal receivedprice, BigDecimal receiveduomQty, BigDecimal utilizedQty, BigDecimal returnedQty, Date manufactureDate, Date expiryDate, BigDecimal vatAmount, Date createdt, Date writedt) {
       this.allStatus = allStatus;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.crmUomByPurchaseuomId = crmUomByPurchaseuomId;
       this.crmUomByReceiveduomId = crmUomByReceiveduomId;
       this.invGoodsreceived = invGoodsreceived;
       this.invStore = invStore;
       this.item = item;
       this.recievedDate = recievedDate;
       this.ref = ref;
       this.batchNo = batchNo;
       this.purchaseqty = purchaseqty;
       this.purchaseuomQty = purchaseuomQty;
       this.purchaseunits = purchaseunits;
       this.purchasePrice = purchasePrice;
       this.receivedqty = receivedqty;
       this.receivedunits = receivedunits;
       this.receivedprice = receivedprice;
       this.receiveduomQty = receiveduomQty;
       this.utilizedQty = utilizedQty;
       this.returnedQty = returnedQty;
       this.manufactureDate = manufactureDate;
       this.expiryDate = expiryDate;
       this.vatAmount = vatAmount;
       this.createdt = createdt;
       this.writedt = writedt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="grn_line_id", unique=true, nullable=false)
    public Integer getGrnLineId() {
        return this.grnLineId;
    }
    
    public void setGrnLineId(Integer grnLineId) {
        this.grnLineId = grnLineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public AllStatus getAllStatus() {
        return this.allStatus;
    }
    
    public void setAllStatus(AllStatus allStatus) {
        this.allStatus = allStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchaseuom_id")
    public CrmUom getCrmUomByPurchaseuomId() {
        return this.crmUomByPurchaseuomId;
    }
    
    public void setCrmUomByPurchaseuomId(CrmUom crmUomByPurchaseuomId) {
        this.crmUomByPurchaseuomId = crmUomByPurchaseuomId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="receiveduom_id")
    public CrmUom getCrmUomByReceiveduomId() {
        return this.crmUomByReceiveduomId;
    }
    
    public void setCrmUomByReceiveduomId(CrmUom crmUomByReceiveduomId) {
        this.crmUomByReceiveduomId = crmUomByReceiveduomId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grn_id")
    public InvGoodsreceived getInvGoodsreceived() {
        return this.invGoodsreceived;
    }
    
    public void setInvGoodsreceived(InvGoodsreceived invGoodsreceived) {
        this.invGoodsreceived = invGoodsreceived;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="store_id")
    public InvStore getInvStore() {
        return this.invStore;
    }
    
    public void setInvStore(InvStore invStore) {
        this.invStore = invStore;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id")
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="recieved_date", length=10)
    public Date getRecievedDate() {
        return this.recievedDate;
    }
    
    public void setRecievedDate(Date recievedDate) {
        this.recievedDate = recievedDate;
    }

    
    @Column(name="ref", length=65535)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="batch_no", length=50)
    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    
    @Column(name="purchaseqty", length=50)
    public String getPurchaseqty() {
        return this.purchaseqty;
    }
    
    public void setPurchaseqty(String purchaseqty) {
        this.purchaseqty = purchaseqty;
    }

    
    @Column(name="purchaseuom_qty", precision=38, scale=20)
    public BigDecimal getPurchaseuomQty() {
        return this.purchaseuomQty;
    }
    
    public void setPurchaseuomQty(BigDecimal purchaseuomQty) {
        this.purchaseuomQty = purchaseuomQty;
    }

    
    @Column(name="purchaseunits")
    public Integer getPurchaseunits() {
        return this.purchaseunits;
    }
    
    public void setPurchaseunits(Integer purchaseunits) {
        this.purchaseunits = purchaseunits;
    }

    
    @Column(name="purchase_price", precision=38, scale=20)
    public BigDecimal getPurchasePrice() {
        return this.purchasePrice;
    }
    
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    
    @Column(name="receivedqty")
    public Integer getReceivedqty() {
        return this.receivedqty;
    }
    
    public void setReceivedqty(Integer receivedqty) {
        this.receivedqty = receivedqty;
    }

    
    @Column(name="receivedunits")
    public Integer getReceivedunits() {
        return this.receivedunits;
    }
    
    public void setReceivedunits(Integer receivedunits) {
        this.receivedunits = receivedunits;
    }

    
    @Column(name="receivedprice", precision=38, scale=20)
    public BigDecimal getReceivedprice() {
        return this.receivedprice;
    }
    
    public void setReceivedprice(BigDecimal receivedprice) {
        this.receivedprice = receivedprice;
    }

    
    @Column(name="receiveduom_qty", precision=38, scale=20)
    public BigDecimal getReceiveduomQty() {
        return this.receiveduomQty;
    }
    
    public void setReceiveduomQty(BigDecimal receiveduomQty) {
        this.receiveduomQty = receiveduomQty;
    }

    
    @Column(name="utilized_qty", precision=38, scale=20)
    public BigDecimal getUtilizedQty() {
        return this.utilizedQty;
    }
    
    public void setUtilizedQty(BigDecimal utilizedQty) {
        this.utilizedQty = utilizedQty;
    }

    
    @Column(name="returned_qty", precision=38, scale=20)
    public BigDecimal getReturnedQty() {
        return this.returnedQty;
    }
    
    public void setReturnedQty(BigDecimal returnedQty) {
        this.returnedQty = returnedQty;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="manufacture_date", length=10)
    public Date getManufactureDate() {
        return this.manufactureDate;
    }
    
    public void setManufactureDate(Date manufactureDate) {
        this.manufactureDate = manufactureDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expiry_date", length=10)
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    
    @Column(name="vat_amount", nullable=false, precision=38, scale=20)
    public BigDecimal getVatAmount() {
        return this.vatAmount;
    }
    
    public void setVatAmount(BigDecimal vatAmount) {
        this.vatAmount = vatAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }




}


