package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IssueLine generated by hbm2java
 */
@Entity
@Table(name="issue_line"
    ,catalog="vxsee"
)
public class IssueLine  implements java.io.Serializable {


     private Integer issueLineId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private int issueId;
     private String purpose;
     private int itemId;
     private int assetId;
     private int storeId;
     private int qtyRequested;
     private int qtyIssued;
     private BigDecimal price;
     private String batchNo;
     private String issuelineMemo;
     private Date createdt;
     private Date writedt;

    public IssueLine() {
    }

	
    public IssueLine(ConLife conLife, int issueId, int itemId, int assetId, int storeId, int qtyRequested, int qtyIssued, BigDecimal price, String batchNo) {
        this.conLife = conLife;
        this.issueId = issueId;
        this.itemId = itemId;
        this.assetId = assetId;
        this.storeId = storeId;
        this.qtyRequested = qtyRequested;
        this.qtyIssued = qtyIssued;
        this.price = price;
        this.batchNo = batchNo;
    }
    public IssueLine(ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, int issueId, String purpose, int itemId, int assetId, int storeId, int qtyRequested, int qtyIssued, BigDecimal price, String batchNo, String issuelineMemo, Date createdt, Date writedt) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.issueId = issueId;
       this.purpose = purpose;
       this.itemId = itemId;
       this.assetId = assetId;
       this.storeId = storeId;
       this.qtyRequested = qtyRequested;
       this.qtyIssued = qtyIssued;
       this.price = price;
       this.batchNo = batchNo;
       this.issuelineMemo = issuelineMemo;
       this.createdt = createdt;
       this.writedt = writedt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="issue_line_id", unique=true, nullable=false)
    public Integer getIssueLineId() {
        return this.issueLineId;
    }
    
    public void setIssueLineId(Integer issueLineId) {
        this.issueLineId = issueLineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

    
    @Column(name="issue_id", nullable=false)
    public int getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(int issueId) {
        this.issueId = issueId;
    }

    
    @Column(name="purpose", length=200)
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    
    @Column(name="item_id", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="asset_id", nullable=false)
    public int getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(int assetId) {
        this.assetId = assetId;
    }

    
    @Column(name="store_id", nullable=false)
    public int getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }

    
    @Column(name="qty_requested", nullable=false)
    public int getQtyRequested() {
        return this.qtyRequested;
    }
    
    public void setQtyRequested(int qtyRequested) {
        this.qtyRequested = qtyRequested;
    }

    
    @Column(name="qty_issued", nullable=false)
    public int getQtyIssued() {
        return this.qtyIssued;
    }
    
    public void setQtyIssued(int qtyIssued) {
        this.qtyIssued = qtyIssued;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="batch_no", nullable=false, length=30)
    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    
    @Column(name="issueline_memo", length=100)
    public String getIssuelineMemo() {
        return this.issuelineMemo;
    }
    
    public void setIssuelineMemo(String issuelineMemo) {
        this.issuelineMemo = issuelineMemo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }




}


