package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemCategory generated by hbm2java
 */
@Entity
@Table(name="item_category"
    ,catalog="vxsee"
)
public class ItemCategory  implements java.io.Serializable {


     private Integer itemCategoryId;
     private String itemCategory;
     private int itemGroupId;
     private int storeId;
     private int chartId;
     private boolean service;
     private String memo;
     private char control;
     private boolean activeInd;
     private int createBy;
     private Date createDt;
     private int modBy;
     private Date modDt;

    public ItemCategory() {
    }

	
    public ItemCategory(String itemCategory, int itemGroupId, int storeId, int chartId, boolean service, char control, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
        this.itemCategory = itemCategory;
        this.itemGroupId = itemGroupId;
        this.storeId = storeId;
        this.chartId = chartId;
        this.service = service;
        this.control = control;
        this.activeInd = activeInd;
        this.createBy = createBy;
        this.createDt = createDt;
        this.modBy = modBy;
        this.modDt = modDt;
    }
    public ItemCategory(String itemCategory, int itemGroupId, int storeId, int chartId, boolean service, String memo, char control, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
       this.itemCategory = itemCategory;
       this.itemGroupId = itemGroupId;
       this.storeId = storeId;
       this.chartId = chartId;
       this.service = service;
       this.memo = memo;
       this.control = control;
       this.activeInd = activeInd;
       this.createBy = createBy;
       this.createDt = createDt;
       this.modBy = modBy;
       this.modDt = modDt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Item_Category_ID", unique=true, nullable=false)
    public Integer getItemCategoryId() {
        return this.itemCategoryId;
    }
    
    public void setItemCategoryId(Integer itemCategoryId) {
        this.itemCategoryId = itemCategoryId;
    }

    
    @Column(name="Item_Category", nullable=false, length=100)
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }

    
    @Column(name="Item_Group_ID", nullable=false)
    public int getItemGroupId() {
        return this.itemGroupId;
    }
    
    public void setItemGroupId(int itemGroupId) {
        this.itemGroupId = itemGroupId;
    }

    
    @Column(name="Store_ID", nullable=false)
    public int getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }

    
    @Column(name="Chart_ID", nullable=false)
    public int getChartId() {
        return this.chartId;
    }
    
    public void setChartId(int chartId) {
        this.chartId = chartId;
    }

    
    @Column(name="Service", nullable=false)
    public boolean isService() {
        return this.service;
    }
    
    public void setService(boolean service) {
        this.service = service;
    }

    
    @Column(name="Memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="Control", nullable=false, length=1)
    public char getControl() {
        return this.control;
    }
    
    public void setControl(char control) {
        this.control = control;
    }

    
    @Column(name="ActiveInd", nullable=false)
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="CreateBy", nullable=false)
    public int getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(int createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDt", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ModBy", nullable=false)
    public int getModBy() {
        return this.modBy;
    }
    
    public void setModBy(int modBy) {
        this.modBy = modBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModDt", nullable=false, length=19)
    public Date getModDt() {
        return this.modDt;
    }
    
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }




}


