package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itemdata generated by hbm2java
 */
@Entity
@Table(name="itemdata"
    ,catalog="vxsee"
)
public class Itemdata  implements java.io.Serializable {


     private Integer itemId;
     private String itemCode;
     private String description;
     private String itemCategoryId;
     private char itemType;
     private long price;
     private float discount;
     private Integer vatId;
     private int puomId;
     private int punits;
     private int duomId;
     private int dunits;
     private String barcode;
     private String barcode2;
     private String manufacturer;
     private Date manufactureDate;
     private Date expireDate;
     private int maxUnits;
     private int minUnits;
     private int reOrderUnits;
     private int reOrderLevel;
     private float commission;
     private boolean fuel;
     private String status;
     private boolean activeInd;
     private String comments;
     private int createBy;
     private Date createDt;
     private int modBy;
     private Date modDt;

    public Itemdata() {
    }

	
    public Itemdata(String description, String itemCategoryId, char itemType, long price, float discount, int puomId, int punits, int duomId, int dunits, Date manufactureDate, Date expireDate, int maxUnits, int minUnits, int reOrderUnits, int reOrderLevel, float commission, boolean fuel, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
        this.description = description;
        this.itemCategoryId = itemCategoryId;
        this.itemType = itemType;
        this.price = price;
        this.discount = discount;
        this.puomId = puomId;
        this.punits = punits;
        this.duomId = duomId;
        this.dunits = dunits;
        this.manufactureDate = manufactureDate;
        this.expireDate = expireDate;
        this.maxUnits = maxUnits;
        this.minUnits = minUnits;
        this.reOrderUnits = reOrderUnits;
        this.reOrderLevel = reOrderLevel;
        this.commission = commission;
        this.fuel = fuel;
        this.activeInd = activeInd;
        this.createBy = createBy;
        this.createDt = createDt;
        this.modBy = modBy;
        this.modDt = modDt;
    }
    public Itemdata(String itemCode, String description, String itemCategoryId, char itemType, long price, float discount, Integer vatId, int puomId, int punits, int duomId, int dunits, String barcode, String barcode2, String manufacturer, Date manufactureDate, Date expireDate, int maxUnits, int minUnits, int reOrderUnits, int reOrderLevel, float commission, boolean fuel, String status, boolean activeInd, String comments, int createBy, Date createDt, int modBy, Date modDt) {
       this.itemCode = itemCode;
       this.description = description;
       this.itemCategoryId = itemCategoryId;
       this.itemType = itemType;
       this.price = price;
       this.discount = discount;
       this.vatId = vatId;
       this.puomId = puomId;
       this.punits = punits;
       this.duomId = duomId;
       this.dunits = dunits;
       this.barcode = barcode;
       this.barcode2 = barcode2;
       this.manufacturer = manufacturer;
       this.manufactureDate = manufactureDate;
       this.expireDate = expireDate;
       this.maxUnits = maxUnits;
       this.minUnits = minUnits;
       this.reOrderUnits = reOrderUnits;
       this.reOrderLevel = reOrderLevel;
       this.commission = commission;
       this.fuel = fuel;
       this.status = status;
       this.activeInd = activeInd;
       this.comments = comments;
       this.createBy = createBy;
       this.createDt = createDt;
       this.modBy = modBy;
       this.modDt = modDt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Item_ID", unique=true, nullable=false)
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="Item_Code", length=20)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    
    @Column(name="Description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Item_Category_ID", nullable=false, length=100)
    public String getItemCategoryId() {
        return this.itemCategoryId;
    }
    
    public void setItemCategoryId(String itemCategoryId) {
        this.itemCategoryId = itemCategoryId;
    }

    
    @Column(name="Item_Type", nullable=false, length=1)
    public char getItemType() {
        return this.itemType;
    }
    
    public void setItemType(char itemType) {
        this.itemType = itemType;
    }

    
    @Column(name="Price", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    
    @Column(name="Discount", nullable=false, precision=12, scale=0)
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }

    
    @Column(name="Vat_ID")
    public Integer getVatId() {
        return this.vatId;
    }
    
    public void setVatId(Integer vatId) {
        this.vatId = vatId;
    }

    
    @Column(name="pUOM_ID", nullable=false)
    public int getPuomId() {
        return this.puomId;
    }
    
    public void setPuomId(int puomId) {
        this.puomId = puomId;
    }

    
    @Column(name="pUnits", nullable=false)
    public int getPunits() {
        return this.punits;
    }
    
    public void setPunits(int punits) {
        this.punits = punits;
    }

    
    @Column(name="dUOM_ID", nullable=false)
    public int getDuomId() {
        return this.duomId;
    }
    
    public void setDuomId(int duomId) {
        this.duomId = duomId;
    }

    
    @Column(name="dUnits", nullable=false)
    public int getDunits() {
        return this.dunits;
    }
    
    public void setDunits(int dunits) {
        this.dunits = dunits;
    }

    
    @Column(name="Barcode", length=50)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="Barcode2", length=20)
    public String getBarcode2() {
        return this.barcode2;
    }
    
    public void setBarcode2(String barcode2) {
        this.barcode2 = barcode2;
    }

    
    @Column(name="Manufacturer", length=200)
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Manufacture_Date", nullable=false, length=10)
    public Date getManufactureDate() {
        return this.manufactureDate;
    }
    
    public void setManufactureDate(Date manufactureDate) {
        this.manufactureDate = manufactureDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Expire_Date", nullable=false, length=10)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    
    @Column(name="Max_Units", nullable=false)
    public int getMaxUnits() {
        return this.maxUnits;
    }
    
    public void setMaxUnits(int maxUnits) {
        this.maxUnits = maxUnits;
    }

    
    @Column(name="Min_Units", nullable=false)
    public int getMinUnits() {
        return this.minUnits;
    }
    
    public void setMinUnits(int minUnits) {
        this.minUnits = minUnits;
    }

    
    @Column(name="ReOrder_Units", nullable=false)
    public int getReOrderUnits() {
        return this.reOrderUnits;
    }
    
    public void setReOrderUnits(int reOrderUnits) {
        this.reOrderUnits = reOrderUnits;
    }

    
    @Column(name="ReOrder_Level", nullable=false)
    public int getReOrderLevel() {
        return this.reOrderLevel;
    }
    
    public void setReOrderLevel(int reOrderLevel) {
        this.reOrderLevel = reOrderLevel;
    }

    
    @Column(name="Commission", nullable=false, precision=12, scale=0)
    public float getCommission() {
        return this.commission;
    }
    
    public void setCommission(float commission) {
        this.commission = commission;
    }

    
    @Column(name="Fuel", nullable=false)
    public boolean isFuel() {
        return this.fuel;
    }
    
    public void setFuel(boolean fuel) {
        this.fuel = fuel;
    }

    
    @Column(name="Status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="ActiveInd", nullable=false)
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="Comments", length=65535)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="CreateBy", nullable=false)
    public int getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(int createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDt", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ModBy", nullable=false)
    public int getModBy() {
        return this.modBy;
    }
    
    public void setModBy(int modBy) {
        this.modBy = modBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModDt", nullable=false, length=19)
    public Date getModDt() {
        return this.modDt;
    }
    
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }




}


