package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemGroup generated by hbm2java
 */
@Entity
@Table(name="item_group"
    ,catalog="vxsee"
)
public class ItemGroup  implements java.io.Serializable {


     private Integer itemGroupId;
     private String itemGroup;
     private int chartId;
     private boolean activeInd;
     private int createBy;
     private Date createDt;
     private int modBy;
     private Date modDt;

    public ItemGroup() {
    }

    public ItemGroup(String itemGroup, int chartId, boolean activeInd, int createBy, Date createDt, int modBy, Date modDt) {
       this.itemGroup = itemGroup;
       this.chartId = chartId;
       this.activeInd = activeInd;
       this.createBy = createBy;
       this.createDt = createDt;
       this.modBy = modBy;
       this.modDt = modDt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Item_Group_ID", unique=true, nullable=false)
    public Integer getItemGroupId() {
        return this.itemGroupId;
    }
    
    public void setItemGroupId(Integer itemGroupId) {
        this.itemGroupId = itemGroupId;
    }

    
    @Column(name="Item_Group", nullable=false, length=100)
    public String getItemGroup() {
        return this.itemGroup;
    }
    
    public void setItemGroup(String itemGroup) {
        this.itemGroup = itemGroup;
    }

    
    @Column(name="Chart_ID", nullable=false)
    public int getChartId() {
        return this.chartId;
    }
    
    public void setChartId(int chartId) {
        this.chartId = chartId;
    }

    
    @Column(name="ActiveInd", nullable=false)
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="CreateBy", nullable=false)
    public int getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(int createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDt", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ModBy", nullable=false)
    public int getModBy() {
        return this.modBy;
    }
    
    public void setModBy(int modBy) {
        this.modBy = modBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ModDt", nullable=false, length=19)
    public Date getModDt() {
        return this.modDt;
    }
    
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }




}


