package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoDtl generated by hbm2java
 */
@Entity
@Table(name="po_dtl"
    ,catalog="vxsee"
)
public class PoDtl  implements java.io.Serializable {


     private Integer purchaseorderLineId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private CrmUom crmUom;
     private Item item;
     private PrcPurchaseOrder prcPurchaseOrder;
     private BigDecimal price;
     private BigDecimal amount;
     private int qty;
     private String memo;
     private Date createdt;
     private Date writedt;

    public PoDtl() {
    }

	
    public PoDtl(ConLife conLife, CrmUom crmUom, Item item, PrcPurchaseOrder prcPurchaseOrder, BigDecimal price, BigDecimal amount, int qty) {
        this.conLife = conLife;
        this.crmUom = crmUom;
        this.item = item;
        this.prcPurchaseOrder = prcPurchaseOrder;
        this.price = price;
        this.amount = amount;
        this.qty = qty;
    }
    public PoDtl(ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, CrmUom crmUom, Item item, PrcPurchaseOrder prcPurchaseOrder, BigDecimal price, BigDecimal amount, int qty, String memo, Date createdt, Date writedt) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.crmUom = crmUom;
       this.item = item;
       this.prcPurchaseOrder = prcPurchaseOrder;
       this.price = price;
       this.amount = amount;
       this.qty = qty;
       this.memo = memo;
       this.createdt = createdt;
       this.writedt = writedt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purchaseorder_line_id", unique=true, nullable=false)
    public Integer getPurchaseorderLineId() {
        return this.purchaseorderLineId;
    }
    
    public void setPurchaseorderLineId(Integer purchaseorderLineId) {
        this.purchaseorderLineId = purchaseorderLineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uom_id", nullable=false)
    public CrmUom getCrmUom() {
        return this.crmUom;
    }
    
    public void setCrmUom(CrmUom crmUom) {
        this.crmUom = crmUom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchaseorder_id", nullable=false)
    public PrcPurchaseOrder getPrcPurchaseOrder() {
        return this.prcPurchaseOrder;
    }
    
    public void setPrcPurchaseOrder(PrcPurchaseOrder prcPurchaseOrder) {
        this.prcPurchaseOrder = prcPurchaseOrder;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }




}


