package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrcPurchaseOrder generated by hbm2java
 */
@Entity
@Table(name="prc_purchase_order"
    ,catalog="vxsee"
)
public class PrcPurchaseOrder  implements java.io.Serializable {


     private Integer purchaseorderId;
     private AllStatus allStatus;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByApprovedby;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private PrcSuppliers prcSuppliers;
     private String purchaseorderCode;
     private Date purchaseorderDate;
     private Date purchaseorderDuedate;
     private String ref;
     private BigDecimal tax;
     private BigDecimal amount;
     private Boolean direct;
     private String comment;
     private Integer seq;
     private Boolean invoiced;
     private Date approvedate;
     private Date createdt;
     private Date writedt;
     private Set<InvGoodsreceived> invGoodsreceiveds = new HashSet<InvGoodsreceived>(0);
     private Set<PoDtl> poDtls = new HashSet<PoDtl>(0);
     private Set<PrcPurchaseOrderLine> prcPurchaseOrderLines = new HashSet<PrcPurchaseOrderLine>(0);

    public PrcPurchaseOrder() {
    }

    public PrcPurchaseOrder(AllStatus allStatus, ConCompany conCompany, ConLife conLife, ConUser conUserByApprovedby, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, PrcSuppliers prcSuppliers, String purchaseorderCode, Date purchaseorderDate, Date purchaseorderDuedate, String ref, BigDecimal tax, BigDecimal amount, Boolean direct, String comment, Integer seq, Boolean invoiced, Date approvedate, Date createdt, Date writedt, Set<InvGoodsreceived> invGoodsreceiveds, Set<PoDtl> poDtls, Set<PrcPurchaseOrderLine> prcPurchaseOrderLines) {
       this.allStatus = allStatus;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByApprovedby = conUserByApprovedby;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.prcSuppliers = prcSuppliers;
       this.purchaseorderCode = purchaseorderCode;
       this.purchaseorderDate = purchaseorderDate;
       this.purchaseorderDuedate = purchaseorderDuedate;
       this.ref = ref;
       this.tax = tax;
       this.amount = amount;
       this.direct = direct;
       this.comment = comment;
       this.seq = seq;
       this.invoiced = invoiced;
       this.approvedate = approvedate;
       this.createdt = createdt;
       this.writedt = writedt;
       this.invGoodsreceiveds = invGoodsreceiveds;
       this.poDtls = poDtls;
       this.prcPurchaseOrderLines = prcPurchaseOrderLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purchaseorder_id", unique=true, nullable=false)
    public Integer getPurchaseorderId() {
        return this.purchaseorderId;
    }
    
    public void setPurchaseorderId(Integer purchaseorderId) {
        this.purchaseorderId = purchaseorderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public AllStatus getAllStatus() {
        return this.allStatus;
    }
    
    public void setAllStatus(AllStatus allStatus) {
        this.allStatus = allStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="approvedby")
    public ConUser getConUserByApprovedby() {
        return this.conUserByApprovedby;
    }
    
    public void setConUserByApprovedby(ConUser conUserByApprovedby) {
        this.conUserByApprovedby = conUserByApprovedby;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public PrcSuppliers getPrcSuppliers() {
        return this.prcSuppliers;
    }
    
    public void setPrcSuppliers(PrcSuppliers prcSuppliers) {
        this.prcSuppliers = prcSuppliers;
    }

    
    @Column(name="purchaseorder_code", length=100)
    public String getPurchaseorderCode() {
        return this.purchaseorderCode;
    }
    
    public void setPurchaseorderCode(String purchaseorderCode) {
        this.purchaseorderCode = purchaseorderCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purchaseorder_date", length=10)
    public Date getPurchaseorderDate() {
        return this.purchaseorderDate;
    }
    
    public void setPurchaseorderDate(Date purchaseorderDate) {
        this.purchaseorderDate = purchaseorderDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purchaseorder_duedate", length=10)
    public Date getPurchaseorderDuedate() {
        return this.purchaseorderDuedate;
    }
    
    public void setPurchaseorderDuedate(Date purchaseorderDuedate) {
        this.purchaseorderDuedate = purchaseorderDuedate;
    }

    
    @Column(name="ref", length=65535)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="tax", precision=10)
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="direct")
    public Boolean getDirect() {
        return this.direct;
    }
    
    public void setDirect(Boolean direct) {
        this.direct = direct;
    }

    
    @Column(name="comment", length=50)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="seq")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="invoiced")
    public Boolean getInvoiced() {
        return this.invoiced;
    }
    
    public void setInvoiced(Boolean invoiced) {
        this.invoiced = invoiced;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="approvedate", length=10)
    public Date getApprovedate() {
        return this.approvedate;
    }
    
    public void setApprovedate(Date approvedate) {
        this.approvedate = approvedate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcPurchaseOrder")
    public Set<InvGoodsreceived> getInvGoodsreceiveds() {
        return this.invGoodsreceiveds;
    }
    
    public void setInvGoodsreceiveds(Set<InvGoodsreceived> invGoodsreceiveds) {
        this.invGoodsreceiveds = invGoodsreceiveds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcPurchaseOrder")
    public Set<PoDtl> getPoDtls() {
        return this.poDtls;
    }
    
    public void setPoDtls(Set<PoDtl> poDtls) {
        this.poDtls = poDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcPurchaseOrder")
    public Set<PrcPurchaseOrderLine> getPrcPurchaseOrderLines() {
        return this.prcPurchaseOrderLines;
    }
    
    public void setPrcPurchaseOrderLines(Set<PrcPurchaseOrderLine> prcPurchaseOrderLines) {
        this.prcPurchaseOrderLines = prcPurchaseOrderLines;
    }




}


