package model;
// Generated Feb 16, 2016 7:40:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrcSuppliers generated by hbm2java
 */
@Entity
@Table(name="prc_suppliers"
    ,catalog="vxsee"
)
public class PrcSuppliers  implements java.io.Serializable {


     private Integer supplierId;
     private AllCurrency allCurrency;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByWritebyId;
     private ConUser conUserByCreatebyId;
     private Paymode paymode;
     private Payterm payterm;
     private String photoPath;
     private Date admnDate;
     private String supplierCode;
     private String supplierName;
     private String othername;
     private String taxcode;
     private String pinno;
     private Boolean credit;
     private BigDecimal creditLimit;
     private BigDecimal openBalance;
     private BigDecimal balance;
     private String location;
     private String contactPerson;
     private String primaryMobileNo;
     private String otherMobileNo;
     private String primaryLandline;
     private String otherLandline;
     private String primaryEmail;
     private String otherEmail;
     private String boxAddress;
     private String boxAddressCode;
     private String boxAddressTown;
     private String physicalAddress;
     private String website;
     private Date createdt;
     private Date writedt;
     private Set<InvGoodsreceived> invGoodsreceiveds = new HashSet<InvGoodsreceived>(0);
     private Set<PrcPurchaseOrder> prcPurchaseOrders = new HashSet<PrcPurchaseOrder>(0);
     private Set<FinReceipt> finReceipts = new HashSet<FinReceipt>(0);
     private Set<ItemPurchase> itemPurchases = new HashSet<ItemPurchase>(0);

    public PrcSuppliers() {
    }

    public PrcSuppliers(AllCurrency allCurrency, ConCompany conCompany, ConLife conLife, ConUser conUserByWritebyId, ConUser conUserByCreatebyId, Paymode paymode, Payterm payterm, String photoPath, Date admnDate, String supplierCode, String supplierName, String othername, String taxcode, String pinno, Boolean credit, BigDecimal creditLimit, BigDecimal openBalance, BigDecimal balance, String location, String contactPerson, String primaryMobileNo, String otherMobileNo, String primaryLandline, String otherLandline, String primaryEmail, String otherEmail, String boxAddress, String boxAddressCode, String boxAddressTown, String physicalAddress, String website, Date createdt, Date writedt, Set<InvGoodsreceived> invGoodsreceiveds, Set<PrcPurchaseOrder> prcPurchaseOrders, Set<FinReceipt> finReceipts, Set<ItemPurchase> itemPurchases) {
       this.allCurrency = allCurrency;
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByWritebyId = conUserByWritebyId;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.paymode = paymode;
       this.payterm = payterm;
       this.photoPath = photoPath;
       this.admnDate = admnDate;
       this.supplierCode = supplierCode;
       this.supplierName = supplierName;
       this.othername = othername;
       this.taxcode = taxcode;
       this.pinno = pinno;
       this.credit = credit;
       this.creditLimit = creditLimit;
       this.openBalance = openBalance;
       this.balance = balance;
       this.location = location;
       this.contactPerson = contactPerson;
       this.primaryMobileNo = primaryMobileNo;
       this.otherMobileNo = otherMobileNo;
       this.primaryLandline = primaryLandline;
       this.otherLandline = otherLandline;
       this.primaryEmail = primaryEmail;
       this.otherEmail = otherEmail;
       this.boxAddress = boxAddress;
       this.boxAddressCode = boxAddressCode;
       this.boxAddressTown = boxAddressTown;
       this.physicalAddress = physicalAddress;
       this.website = website;
       this.createdt = createdt;
       this.writedt = writedt;
       this.invGoodsreceiveds = invGoodsreceiveds;
       this.prcPurchaseOrders = prcPurchaseOrders;
       this.finReceipts = finReceipts;
       this.itemPurchases = itemPurchases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="supplier_id", unique=true, nullable=false)
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="currency_id")
    public AllCurrency getAllCurrency() {
        return this.allCurrency;
    }
    
    public void setAllCurrency(AllCurrency allCurrency) {
        this.allCurrency = allCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life")
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paymode_id")
    public Paymode getPaymode() {
        return this.paymode;
    }
    
    public void setPaymode(Paymode paymode) {
        this.paymode = paymode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payterm_id")
    public Payterm getPayterm() {
        return this.payterm;
    }
    
    public void setPayterm(Payterm payterm) {
        this.payterm = payterm;
    }

    
    @Column(name="photo_path", length=100)
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="admn_date", length=19)
    public Date getAdmnDate() {
        return this.admnDate;
    }
    
    public void setAdmnDate(Date admnDate) {
        this.admnDate = admnDate;
    }

    
    @Column(name="supplier_code", length=15)
    public String getSupplierCode() {
        return this.supplierCode;
    }
    
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    
    @Column(name="supplier_name", length=20)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="othername", length=50)
    public String getOthername() {
        return this.othername;
    }
    
    public void setOthername(String othername) {
        this.othername = othername;
    }

    
    @Column(name="taxcode", length=50)
    public String getTaxcode() {
        return this.taxcode;
    }
    
    public void setTaxcode(String taxcode) {
        this.taxcode = taxcode;
    }

    
    @Column(name="pinno", length=50)
    public String getPinno() {
        return this.pinno;
    }
    
    public void setPinno(String pinno) {
        this.pinno = pinno;
    }

    
    @Column(name="credit")
    public Boolean getCredit() {
        return this.credit;
    }
    
    public void setCredit(Boolean credit) {
        this.credit = credit;
    }

    
    @Column(name="credit_limit", precision=38, scale=20)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="open_balance", precision=38, scale=20)
    public BigDecimal getOpenBalance() {
        return this.openBalance;
    }
    
    public void setOpenBalance(BigDecimal openBalance) {
        this.openBalance = openBalance;
    }

    
    @Column(name="balance", precision=38, scale=20)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="location", length=200)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="contact_person", length=50)
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    
    @Column(name="primary_mobile_no", length=50)
    public String getPrimaryMobileNo() {
        return this.primaryMobileNo;
    }
    
    public void setPrimaryMobileNo(String primaryMobileNo) {
        this.primaryMobileNo = primaryMobileNo;
    }

    
    @Column(name="other_mobile_no", length=50)
    public String getOtherMobileNo() {
        return this.otherMobileNo;
    }
    
    public void setOtherMobileNo(String otherMobileNo) {
        this.otherMobileNo = otherMobileNo;
    }

    
    @Column(name="primary_landline", length=50)
    public String getPrimaryLandline() {
        return this.primaryLandline;
    }
    
    public void setPrimaryLandline(String primaryLandline) {
        this.primaryLandline = primaryLandline;
    }

    
    @Column(name="other_landline", length=50)
    public String getOtherLandline() {
        return this.otherLandline;
    }
    
    public void setOtherLandline(String otherLandline) {
        this.otherLandline = otherLandline;
    }

    
    @Column(name="primary_email", length=50)
    public String getPrimaryEmail() {
        return this.primaryEmail;
    }
    
    public void setPrimaryEmail(String primaryEmail) {
        this.primaryEmail = primaryEmail;
    }

    
    @Column(name="other_email", length=50)
    public String getOtherEmail() {
        return this.otherEmail;
    }
    
    public void setOtherEmail(String otherEmail) {
        this.otherEmail = otherEmail;
    }

    
    @Column(name="box_address", length=50)
    public String getBoxAddress() {
        return this.boxAddress;
    }
    
    public void setBoxAddress(String boxAddress) {
        this.boxAddress = boxAddress;
    }

    
    @Column(name="box_address_code", length=10)
    public String getBoxAddressCode() {
        return this.boxAddressCode;
    }
    
    public void setBoxAddressCode(String boxAddressCode) {
        this.boxAddressCode = boxAddressCode;
    }

    
    @Column(name="box_address_town", length=50)
    public String getBoxAddressTown() {
        return this.boxAddressTown;
    }
    
    public void setBoxAddressTown(String boxAddressTown) {
        this.boxAddressTown = boxAddressTown;
    }

    
    @Column(name="physical_address", length=50)
    public String getPhysicalAddress() {
        return this.physicalAddress;
    }
    
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }

    
    @Column(name="website", length=50)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcSuppliers")
    public Set<InvGoodsreceived> getInvGoodsreceiveds() {
        return this.invGoodsreceiveds;
    }
    
    public void setInvGoodsreceiveds(Set<InvGoodsreceived> invGoodsreceiveds) {
        this.invGoodsreceiveds = invGoodsreceiveds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcSuppliers")
    public Set<PrcPurchaseOrder> getPrcPurchaseOrders() {
        return this.prcPurchaseOrders;
    }
    
    public void setPrcPurchaseOrders(Set<PrcPurchaseOrder> prcPurchaseOrders) {
        this.prcPurchaseOrders = prcPurchaseOrders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcSuppliers")
    public Set<FinReceipt> getFinReceipts() {
        return this.finReceipts;
    }
    
    public void setFinReceipts(Set<FinReceipt> finReceipts) {
        this.finReceipts = finReceipts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prcSuppliers")
    public Set<ItemPurchase> getItemPurchases() {
        return this.itemPurchases;
    }
    
    public void setItemPurchases(Set<ItemPurchase> itemPurchases) {
        this.itemPurchases = itemPurchases;
    }




}


