package model;
// Generated Feb 9, 2016 11:32:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseRequisition generated by hbm2java
 */
@Entity
@Table(name="purchase_requisition"
    ,catalog="vxsee"
)
public class PurchaseRequisition  implements java.io.Serializable {


     private Integer purchaseRequisitionId;
     private ConCompany conCompany;
     private ConLife conLife;
     private ConUser conUserByCreatebyId;
     private ConUser conUserByWritebyId;
     private String requisitionCode;
     private Date requisitionDate;
     private int employeeId;
     private String memo;
     private String status;
     private int taskId;
     private int customerProjectId;
     private int issueId;
     private int reviewedby;
     private Date reviewedate;
     private int approvedby;
     private Date approvedate;
     private String rejectReason;
     private int issued;
     private Date createdt;
     private Date writedt;
     private Set<PurchaseRequisitionLine> purchaseRequisitionLines = new HashSet<PurchaseRequisitionLine>(0);

    public PurchaseRequisition() {
    }

	
    public PurchaseRequisition(ConLife conLife, String requisitionCode, Date requisitionDate, int employeeId, String memo, String status, int taskId, int customerProjectId, int issueId, int reviewedby, Date reviewedate, int approvedby, Date approvedate, String rejectReason, int issued) {
        this.conLife = conLife;
        this.requisitionCode = requisitionCode;
        this.requisitionDate = requisitionDate;
        this.employeeId = employeeId;
        this.memo = memo;
        this.status = status;
        this.taskId = taskId;
        this.customerProjectId = customerProjectId;
        this.issueId = issueId;
        this.reviewedby = reviewedby;
        this.reviewedate = reviewedate;
        this.approvedby = approvedby;
        this.approvedate = approvedate;
        this.rejectReason = rejectReason;
        this.issued = issued;
    }
    public PurchaseRequisition(ConCompany conCompany, ConLife conLife, ConUser conUserByCreatebyId, ConUser conUserByWritebyId, String requisitionCode, Date requisitionDate, int employeeId, String memo, String status, int taskId, int customerProjectId, int issueId, int reviewedby, Date reviewedate, int approvedby, Date approvedate, String rejectReason, int issued, Date createdt, Date writedt, Set<PurchaseRequisitionLine> purchaseRequisitionLines) {
       this.conCompany = conCompany;
       this.conLife = conLife;
       this.conUserByCreatebyId = conUserByCreatebyId;
       this.conUserByWritebyId = conUserByWritebyId;
       this.requisitionCode = requisitionCode;
       this.requisitionDate = requisitionDate;
       this.employeeId = employeeId;
       this.memo = memo;
       this.status = status;
       this.taskId = taskId;
       this.customerProjectId = customerProjectId;
       this.issueId = issueId;
       this.reviewedby = reviewedby;
       this.reviewedate = reviewedate;
       this.approvedby = approvedby;
       this.approvedate = approvedate;
       this.rejectReason = rejectReason;
       this.issued = issued;
       this.createdt = createdt;
       this.writedt = writedt;
       this.purchaseRequisitionLines = purchaseRequisitionLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purchase_requisition_id", unique=true, nullable=false)
    public Integer getPurchaseRequisitionId() {
        return this.purchaseRequisitionId;
    }
    
    public void setPurchaseRequisitionId(Integer purchaseRequisitionId) {
        this.purchaseRequisitionId = purchaseRequisitionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public ConCompany getConCompany() {
        return this.conCompany;
    }
    
    public void setConCompany(ConCompany conCompany) {
        this.conCompany = conCompany;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="life", nullable=false)
    public ConLife getConLife() {
        return this.conLife;
    }
    
    public void setConLife(ConLife conLife) {
        this.conLife = conLife;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="createby_id")
    public ConUser getConUserByCreatebyId() {
        return this.conUserByCreatebyId;
    }
    
    public void setConUserByCreatebyId(ConUser conUserByCreatebyId) {
        this.conUserByCreatebyId = conUserByCreatebyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="writeby_id")
    public ConUser getConUserByWritebyId() {
        return this.conUserByWritebyId;
    }
    
    public void setConUserByWritebyId(ConUser conUserByWritebyId) {
        this.conUserByWritebyId = conUserByWritebyId;
    }

    
    @Column(name="requisition_code", nullable=false, length=50)
    public String getRequisitionCode() {
        return this.requisitionCode;
    }
    
    public void setRequisitionCode(String requisitionCode) {
        this.requisitionCode = requisitionCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="requisition_date", nullable=false, length=10)
    public Date getRequisitionDate() {
        return this.requisitionDate;
    }
    
    public void setRequisitionDate(Date requisitionDate) {
        this.requisitionDate = requisitionDate;
    }

    
    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="memo", nullable=false, length=50)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="task_id", nullable=false)
    public int getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

    
    @Column(name="customer_project_id", nullable=false)
    public int getCustomerProjectId() {
        return this.customerProjectId;
    }
    
    public void setCustomerProjectId(int customerProjectId) {
        this.customerProjectId = customerProjectId;
    }

    
    @Column(name="issue_id", nullable=false)
    public int getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(int issueId) {
        this.issueId = issueId;
    }

    
    @Column(name="reviewedby", nullable=false)
    public int getReviewedby() {
        return this.reviewedby;
    }
    
    public void setReviewedby(int reviewedby) {
        this.reviewedby = reviewedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reviewedate", nullable=false, length=19)
    public Date getReviewedate() {
        return this.reviewedate;
    }
    
    public void setReviewedate(Date reviewedate) {
        this.reviewedate = reviewedate;
    }

    
    @Column(name="approvedby", nullable=false)
    public int getApprovedby() {
        return this.approvedby;
    }
    
    public void setApprovedby(int approvedby) {
        this.approvedby = approvedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="approvedate", nullable=false, length=19)
    public Date getApprovedate() {
        return this.approvedate;
    }
    
    public void setApprovedate(Date approvedate) {
        this.approvedate = approvedate;
    }

    
    @Column(name="reject_reason", nullable=false, length=50)
    public String getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    
    @Column(name="issued", nullable=false)
    public int getIssued() {
        return this.issued;
    }
    
    public void setIssued(int issued) {
        this.issued = issued;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdt", length=19)
    public Date getCreatedt() {
        return this.createdt;
    }
    
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="writedt", length=19)
    public Date getWritedt() {
        return this.writedt;
    }
    
    public void setWritedt(Date writedt) {
        this.writedt = writedt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseRequisition")
    public Set<PurchaseRequisitionLine> getPurchaseRequisitionLines() {
        return this.purchaseRequisitionLines;
    }
    
    public void setPurchaseRequisitionLines(Set<PurchaseRequisitionLine> purchaseRequisitionLines) {
        this.purchaseRequisitionLines = purchaseRequisitionLines;
    }




}


