// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../js/bootstrap-datepicker.js');
require('../js/bootstrap-transition.js');
require('../js/bootstrap-alert.js');
require('../js/bootstrap-button.js');
require('../js/bootstrap-carousel.js');
require('../js/bootstrap-collapse.js');
require('../js/bootstrap-dropdown.js');
require('../js/bootstrap-modal.js');
require('../js/bootstrap-tooltip.js');
require('../js/bootstrap-popover.js');
require('../js/bootstrap-scrollspy.js');
require('../js/bootstrap-tab.js');
require('../js/bootstrap-affix.js');